/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-02-07 07:46:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import beans.CancelOrderOutputBean;
import java.util.ArrayList;
import java.sql.ResultSet;
import dao.CancelOrderDAO;
import beans.CancelOrderInputBean;

public final class CancelOrderAjaxResponse_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      beans.CancelOrderInputBean cancelOrderInputBean = null;
      cancelOrderInputBean = (beans.CancelOrderInputBean) _jspx_page_context.getAttribute("cancelOrderInputBean", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (cancelOrderInputBean == null){
        cancelOrderInputBean = new beans.CancelOrderInputBean();
        _jspx_page_context.setAttribute("cancelOrderInputBean", cancelOrderInputBean, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
        out.write('\n');
        out.write('	');
        org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("cancelOrderInputBean"), request);
        out.write('\n');
      }
      out.write("\n");
      out.write("\t\n");
      out.write("\t");

	String ajaxOption = request.getParameter("ajaxOption");
	if(ajaxOption.equals("getOrderDetails")){
	
      out.write("\n");
      out.write("\t<table border=\"1\" class=\"item3\" style=\"border-collapse: collapse;max-height: 100%;text-align: center;\">\n");
      out.write("    \t <thead style=\"\">\n");
      out.write("\t\t\t<tr style=\"max-height: 7px;\">\n");
      out.write("\t\t\t\t<td width=\"5%\"><b>OrderNumber</b></td>\n");
      out.write("\t\t\t\t<td width=\"10%%\"><b>Order Date</b></td>\n");
      out.write("\t\t\t\t<td width=\"15%\"><b>Customer Name</b></td>\n");
      out.write("\t\t\t\t<td width=\"10%\"><b>Payment Type</b></td>\n");
      out.write("\t\t\t\t<td width=\"10%\"><b>Entered By</b></td>\n");
      out.write("\t\t\t\t<td width=\"10%\"><b>Status</b></td>\n");
      out.write("\t\t\t\t<td width=\"10%\"></td>\t\t\t\t\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t</thead><tbody style=\"overflow: auto;max-height: 200px;\">\n");
      out.write("\t\t");

			CancelOrderDAO cancelOrderDAO = new CancelOrderDAO();
			int i =0;
			ArrayList<CancelOrderOutputBean> listCancelOrderOutputBeans = cancelOrderDAO.getOrderDetails(cancelOrderInputBean);
			for(CancelOrderOutputBean bean : listCancelOrderOutputBeans){
			
      out.write("\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<tr id=\"id");
      out.print(i);
      out.write("\" style=\"max-height: 7px;\">\n");
      out.write("\t\t\t\t<td  width=\"5%\">");
      out.print(bean.getOrderNumber() );
      out.write("</td>\n");
      out.write("\t\t\t\t<td width=\"10%\">");
      out.print(bean.getOrderDate() );
      out.write("</td>\n");
      out.write("\t\t\t\t<td width=\"15%\">");
      out.print(bean.getCustName() );
      out.write("</td>\n");
      out.write("\t\t\t\t<td width=\"10%\">");
      out.print(bean.getPayment_type_desc() );
      out.write("</td>\n");
      out.write("\t\t\t\t<td width=\"10%\">");
      out.print(bean.getEnterd_by() );
      out.write("</td>\n");
      out.write("\t\t\t\t<td width=\"10%\">");
      out.print(bean.getStatusCode() );
      out.write("</td>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<td width=\"10%\"><button onclick=\"cancelOrder('");
      out.print(bean.getOrderNumber());
      out.write("','id");
      out.print(i);
      out.write("');return false;\" style=\"height: inherit; \">Cancel Order </button></td>\t\t\t\t\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t");

				i++;
			
			}
			
		
      out.write("</tbody>\n");
      out.write("\t</table>\n");
      out.write("\t\n");
      out.write("\t");

	}
	else if(ajaxOption.equals("cancelOrder")){
		String orderNumber = request.getParameter("orderNum");
		CancelOrderDAO cancelOrderDAO = new CancelOrderDAO();
		boolean flag =  cancelOrderDAO.cancelOrder(orderNumber);
		out.print("order cancelled .. ");
		
		
	}
	
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
