/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-02-21 05:51:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import item.ManageItem;

public final class checkedOrderAjaxResponse_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
	
String ajaxCallOption = request.getParameter("ajaxCallOption");


if(ajaxCallOption.equals("checkOrderExistance")){
	String orderNo = request.getParameter("orderNo");
	order.ManageOrder mo = new order.ManageOrder("jdbc/js");
		boolean result = mo.isExistOrderNumber(orderNo,"SUBMITTED");    	
    	if(result){
    		out.println("Exist");
    	}else{
    		out.println("NotExist");
    	}  	
    	mo.closeAll();
}else if(ajaxCallOption.equals("getCustInfo")){	
			
	String cust_code, custname,phone, building, building_no,wing, block,add1, add2, add3; 
	String area, station;	
	String orderNo = request.getParameter("orderNo");
	
	customer.ManageCustomer mc = new customer.ManageCustomer("jdbc/js");
	mc.getCustInfoByOrderNumber(orderNo);
	while(mc.rs.next()){
		cust_code = mc.rs.getString("custcode");
		custname = mc.rs.getString("custname");
		phone = mc.rs.getString("phone");
		building = mc.rs.getString("building");
		building_no = mc.rs.getString("building_no");
		wing = mc.rs.getString("wing");
		block = mc.rs.getString("block");
		add1 = mc.rs.getString("add1");
		add2 = mc.rs.getString("add2");
		area = mc.rs.getString("area");
		station = mc.rs.getString("station");

      out.write("\n");
      out.write("\t\t<div class=\"roundedDiv\"  style=\"background-color: #BEF781;border:1px solid black; width: 100%;\">\n");
      out.write("\t\t <table  class=\"custorderinfo\"  style=\"width:100%;\">\n");
      out.write("\t\t  <thead>\n");
      out.write("\t\t   <tr>\n");
      out.write("\t  \t\t <th width=\"8%\"><b>Customer_Code  </b></th> <td width=\"8%\">: ");
 out.println(cust_code);
      out.write("&nbsp;</td>\t\t\t  \t  \t  \t\n");
      out.write("\t\t\t  <th width=\"8%\"><b>Customer_Name  </b> </th> <td width=\"16%\">: ");
 out.println(custname);
      out.write("&nbsp;</td>\t\t\t  \n");
      out.write("\t\t\t  <th width=\"8%\"><b>Phone_Number  </b> </th> <td width=\"10%\">: ");
 out.println(phone);
      out.write("&nbsp;</td>\t\t\t  \t\t\t\n");
      out.write("\t\t\t  <th width=\"3%\"><b>Building  </b></th> <td width=\"12%\">: ");
 out.println(building);
      out.write("&nbsp;</td>\t\t\t  \n");
      out.write("\t\t\t  <th width=\"5%\"><b>Building_No.  </b> </th> <td width=\"9%\">: ");
 out.println(building_no);
      out.write("&nbsp;</td>\t\t\t\n");
      out.write("\t\t\t  <th width=\"2%\"><b>Wing  </b></th> <td width=\"5%\">: ");
 out.println(wing);
      out.write("</td>\t\t  \n");
      out.write("\t\t   </tr>\n");
      out.write("\t\t   <tr><td height=\"10px;\"></td></tr>\n");
      out.write("\t\t   <tr>\n");
      out.write("            <th><b>Block   </b> </th> <td>: ");
 out.println(block);
      out.write("&nbsp;</td> \t\t\t\n");
      out.write("\t\t\t<th><b>Address1 </b></th> <td> : ");
 out.println(add1);
      out.write("&nbsp;</td> \t\t\t \n");
      out.write("\t\t\t<th><b>Address2  </b> </th> <td>: ");
 out.println(add2);
      out.write("&nbsp;</td> \t\t\t\n");
      out.write("\t\t\t<th><b>Area </b></th><td>  : ");
 out.println(area);
      out.write("&nbsp;</td> \t\t\t \n");
      out.write("\t\t\t<th><b>Station  </b> </th> <td> : ");
out.println(station);
      out.write("&nbsp;</td> \n");
      out.write("\t       </tr>\n");
      out.write("\t\t  </thead>\t\t\t\n");
      out.write("\t\t </table>\n");
      out.write("\t\t</div>\n");

	}
	mc.closeAll();
}else if(ajaxCallOption.equals("getOrderInfo")){
	String orderNo = request.getParameter("orderNo");
	order.ManageOrder mo = new order.ManageOrder("jdbc/js");
	mo.getCheckedOrderInfo(orderNo);
	
	String order_num, order_date, total_items, 	payment_type_desc, status_code, remark;
	float total_value, total_value_discount,saving,total_value_mrp;
	while(mo.rs.next()){
		
		order_num = mo.rs.getString("order_num");
		order_date = mo.rs.getString("order_date");
		total_items = mo.rs.getString("total_items");
		total_value = mo.rs.getFloat("total_value");
		total_value_mrp = mo.rs.getFloat("total_value_mrp");
		total_value_discount = mo.rs.getFloat("total_value_discount");
		payment_type_desc = mo.rs.getString("payment_type_desc");
		status_code = mo.rs.getString("status_code");
		remark = mo.rs.getString("remark");
		
		saving = total_value_mrp - total_value + total_value_discount;

      out.write("\n");
      out.write("\t\t<div class=\"roundedDiv\" style=\"background-color: #BEF781; border:1px solid black; width: 100%;\">\n");
      out.write(" \t\t  <table class=\"custorderinfo\"  style=\"width:100%;\">\n");
      out.write(" \t\t  <tr>\n");
      out.write("\t\t\t <th width=\"8%\">Order_Number</th> \n");
      out.write("\t\t\t <td width=\"8%\">: ");
 out.println(order_num);
      out.write("&nbsp;</td>\n");
      out.write("\t\t\t <th width=\"8%\">Order_Date</th>\n");
      out.write("\t\t\t <td width=\"16%\">:");
 out.println(order_date);
      out.write("&nbsp;</td>\n");
      out.write("\t\t\t <th width=\"8%\">Total_Items</th> \n");
      out.write("\t\t\t <td width=\"10%\">: ");
 out.println(total_items);
      out.write("&nbsp;</td>\n");
      out.write("\t\t\t <th width=\"3%\">Total_Price</th> \n");
      out.write("\t\t\t <td width=\"12%\">: ");
 out.println(total_value);
      out.write("&nbsp;</td>\n");
      out.write("\t\t\t  <th width=\"5%\"></th> \n");
      out.write("\t\t\t  <td width=\"9%\">&nbsp;</td>\t\t\t\n");
      out.write("\t\t\t  <th width=\"2%\"></th> \n");
      out.write("\t\t\t  <td width=\"5%\"></td>\t\t  \n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr><td height=\"10px;\"></td></tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<th >Total_Saving</th> <td >: ");
 out.println(saving);
      out.write("&nbsp;</td>\n");
      out.write("\t\t\t\t\t<th >Payment_Type</th> <td>: ");
 out.println(payment_type_desc);
      out.write("&nbsp;</td>\n");
      out.write("\t\t\t\t\t<th >Order_Status </th> <td >:");
 out.println(status_code);
      out.write("&nbsp;</td>\n");
      out.write("\t\t\t\t\t<th >Remark</th> <td >: ");
 out.println(remark);
      out.write("&nbsp;</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t \t  </table>\n");
      out.write("\t\t </div>\n");

	}
	mo.closeAll();
}else if(ajaxCallOption.equals("getOrderItemInfo")){
	String orderNo = request.getParameter("orderNo");
	order.ManageOrder mo = new order.ManageOrder("jdbc/js");
	mo.getOrderItemDetails(orderNo);
	String barcode, item_code, item_name, item_weight, rate, qty, price, remark,itemGroupCode;

      out.write("\n");
      out.write("\t<table id=\"itemTable\" class=\"genericTbl\" style=\"width:100%;\">\n");
      out.write("\t <thead>\t  \n");
      out.write("\t  <tr  style=\"position:relative;top:expression(document.all['OrderItemInfoDiv'].scrollTop);background-color:#a43333;\" >\n");
      out.write("\t  \t<th style=\"background-color:#a43333;color:#FFFFFF;\">Item Code</th>\n");
      out.write("\t  \t<th style=\"background-color:#a43333;color:#FFFFFF;\">Item Name</th>\n");
      out.write("\t  \t<th style=\"background-color:#a43333;color:#FFFFFF;\">Item Weight</th>\n");
      out.write("\t  \t<th style=\"background-color:#a43333;color:#FFFFFF;\">Rate</th>\n");
      out.write("\t  \t<th style=\"background-color:#a43333;color:#FFFFFF;\">Order Quantity</th>\n");
      out.write("\t  \t<th style=\"background-color:#a43333;color:#FFFFFF;\">Accounted Quantity</th>\n");
      out.write("\t  \t<th style=\"background-color:#a43333;color:#FFFFFF;\">Total Price</th>\n");
      out.write("\t  \t<th style=\"background-color:#a43333;color:#FFFFFF;\">Remark</th>\n");
      out.write("\t  </tr>\n");
      out.write("\t </thead>\n");
      out.write("\t <tbody>\n");

	while(mo.rs.next()){
		barcode = mo.rs.getString("barcode");
		item_code = mo.rs.getString("item_code");
		item_name = mo.rs.getString("item_name");
		item_weight = mo.rs.getString("item_weight");
		rate = mo.rs.getString("rate");
		qty = mo.rs.getString("qty");
		price = mo.rs.getString("price");
		remark = mo.rs.getString("remark");
		itemGroupCode = mo.rs.getString("item_group_code");

      out.write("\n");
      out.write(" \n");
      out.write("\t <tr>\t  \n");
      out.write("\t  <td><input type=\"text\" name=\"iCode\" id=\"iCode\" value=\"");
      out.print(item_code);
      out.write("\" class=\"hideTextField\"  size=\"7\" readonly=\"readonly\" style=\"font-size: 12;\"/></td>\n");
      out.write("\t  <td><input type=\"text\" name=\"iName\" id=\"iName\" value=\"");
      out.print(item_name);
      out.write("\" class=\"hideTextField\"  size=\"40\" readonly=\"readonly\" style=\"font-size: 12;\"/></td>\n");
      out.write("\t  <td><input type=\"text\" name=\"iWeight\" id=\"iWeight\" value=\"");
      out.print(item_weight);
      out.write("\" class=\"hideTextField\"  size=\"5\" readonly=\"readonly\" style=\"font-size: 12;\"/></td>\n");
      out.write("\t  <td><input type=\"text\" name=\"iRate\" id=\"iRate\" value=\"");
      out.print(rate);
      out.write("\" class=\"hideTextField\" size=\"5\"  readonly=\"readonly\" style=\"font-size: 12;\"/></td>\n");
      out.write("\t  <td><input type=\"text\" name=\"iOrderQty\" id=\"iOrderQty\" value=\"");
      out.print(qty);
      out.write("\" class=\"hideTextField\"  size=\"5\" readonly=\"readonly\" style=\"font-size: 12;\"/></td>\n");
      out.write("\t  <td><input type=\"text\" name=\"iAccountedQty\" id=\"iAccountedQty\" value=\"\" class=\"hideTextField\"  size=\"5\" readonly=\"readonly\" style=\"font-size: 12;\"/></td>\n");
      out.write("\t  <td><input type=\"text\" name=\"iPrice\" id=\"iPrice\" value=\"");
      out.print(price);
      out.write("\" class=\"hideTextField\"  size=\"5\" readonly=\"readonly\" style=\"font-size: 12;\"/></td>\n");
      out.write("\t  <td><input type=\"text\" name=\"iRemark\" id=\"iRemark\" value=\"");
      out.print(remark);
      out.write("\" class=\"hideTextField\"  size=\"20\" readonly=\"readonly\" /></td>\n");
      out.write("\t  <td><input type=\"hidden\" name=\"hBarcode\" id=\"");
      out.print(barcode);
      out.write("\" value=\"");
      out.print(barcode);
      out.write("\"  class=\"hideTextField\"/></td>\n");
      out.write("\t  <td style=\"display: none;\"><input type=\"hidden\" name=\"hItemGroupCode\" value=\"");
      out.print(itemGroupCode);
      out.write("\"  class=\"hideTextField\"/></td>\n");
      out.write("\t </tr>\t\n");
			
	}

      out.write("\n");
      out.write(" \t </tbody>\n");
      out.write("\t</table>\t\n");

	mo.closeAll();
}	else if(ajaxCallOption.equals("getItemNames")){
	String serachItemName = request.getParameter("serachItemName");
	ManageItem mi = new ManageItem("jdbc/js");
	mi.listItemBarCode("",serachItemName);
	String barcode, item_code, item_name, item_weight, rate, mrp, deal_amt, deal_qty,itemGroupCode;

      out.write("\n");
      out.write("\t<table id=\"itemTable\" class=\"genericTbl\" style=\"width:100%;\">\n");
      out.write("\t <thead>\t  \n");
      out.write("\t  <tr  style=\"position:relative;top:expression(document.all['ResponseDiv'].scrollTop);\">\n");
      out.write("\t  \t<th>Item Code</th>\n");
      out.write("\t  \t<th>Item Name</th>\n");
      out.write("\t  \t<th>Item Weight</th>\n");
      out.write("\t  \t<th>Rate</th>\n");
      out.write("\t  \t<th>Order Quantity</th>\n");
      out.write("\t  \t<th>Accounted Quantity</th>\n");
      out.write("\t  \t<th>Total Price</th>\n");
      out.write("\t  \t<th>Remark</th>\n");
      out.write("\t  </tr>\n");
      out.write("\t </thead>\n");
      out.write("\t <tbody>\n");

	while(mi.rs.next()){
		barcode = mi.rs.getString("barcode");
		item_code = mi.rs.getString("item_code");
		item_name = mi.rs.getString("item_name");
		item_weight = mi.rs.getString("item_weight");
		rate = mi.rs.getString("item_rate");
		mrp = mi.rs.getString("item_mrp");
		deal_amt = mi.rs.getString("deal_amount");
		deal_qty = mi.rs.getString("deal_on_qty");
		itemGroupCode = mi.rs.getString("item_group_code");

      out.write("\n");
      out.write(" \n");
      out.write("\t <tr onclick=\"funSelItem();\">\t  \n");
      out.write("\t  <td><input type=\"text\" name=\"siCode\" id=\"iCode\" value=\"");
      out.print(item_code);
      out.write("\" class=\"hideTextField\" size=\"7\" readonly=\"readonly\"/></td>\n");
      out.write("\t  <td><a href=\"funSelItem();\"><input type=\"text\" name=\"siName\" id=\"iName\" value=\"");
      out.print(item_name);
      out.write("\" class=\"hideTextField\" size=\"40\" readonly=\"readonly\"/></a></td>\n");
      out.write("\t  <td><input type=\"text\" name=\"siWeight\" id=\"iWeight\" value=\"");
      out.print(item_weight);
      out.write("\" class=\"hideTextField\" size=\"5\" readonly=\"readonly\"/></td>\n");
      out.write("\t  <td><input type=\"text\" name=\"siRate\" id=\"iRate\" value=\"");
      out.print(rate);
      out.write("\" class=\"hideTextField\" size=\"5\" readonly=\"readonly\"/></td>\n");
      out.write("\t  <td><input type=\"text\" name=\"siOrderQty\" id=\"iOrderQty\" value=\"");
      out.print(mrp);
      out.write("\" class=\"hideTextField\" size=\"5\" readonly=\"readonly\"/></td>\n");
      out.write("\t  <td><input type=\"text\" name=\"siPrice\" id=\"iPrice\" value=\"");
      out.print(deal_amt);
      out.write("\" class=\"hideTextField\" size=\"5\" readonly=\"readonly\"/></td>\n");
      out.write("\t  <td><input type=\"text\" name=\"siRemark\" id=\"iRemark\" value=\"");
      out.print(deal_qty);
      out.write("\" class=\"hideTextField\" size=\"20\" readonly=\"readonly\"/></td>\n");
      out.write("\t  <td><input type=\"hidden\" name=\"hsBarcode\" id=\"");
      out.print(barcode);
      out.write("\" value=\"");
      out.print(barcode);
      out.write("\" class=\"hideTextField\"/></td>\n");
      out.write("\t  <td><input type=\"hidden\" name=\"hsItemGroupCode\" value=\"");
      out.print(itemGroupCode);
      out.write("\" class=\"hideTextField\"/></td>\n");
      out.write("\t </tr>\t\n");
			
	}

      out.write("\n");
      out.write(" \t </tbody>\n");
      out.write("\t</table>\t\n");

	mi.closeAll();
}else if(ajaxCallOption.equals("showItemNames")){
	ManageItem mi = new ManageItem("jdbc/js");
	ResultSet resultSet = mi.getItemNames();
	
      out.write("\n");
      out.write("\t<select>\n");
      out.write("\t\t<option value=\"\">select</option>\n");
      out.write("\t\t");

			while(resultSet.next()){
				
      out.write("\n");
      out.write("\t\t\t\t<option value=\"");
      out.print(resultSet.getString(1));
      out.write('"');
      out.write('>');
      out.print(resultSet.getString(2) );
      out.write("</option>\n");
      out.write("\t\t\t\t");

			}
		
      out.write("\n");
      out.write("\t</select>\n");
      out.write("\t");

	mi.closeAll();
	
}	


    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
