/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-02-24 11:52:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import payment.*;

public final class communicationForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/communication.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/ReceivePayment.js\"></script>\r\n");
      out.write("<script language=\"javascript\" src=\"js/codethatcalendarstd.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/popup.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("var caldef1 = {\r\n");
      out.write("firstday:0,\r\n");
      out.write("dtype:'dd/MM/yyyy',\r\n");
      out.write("width:250,\r\n");
      out.write("windoww:300,\r\n");
      out.write("windowh:200,\r\n");
      out.write("border_width:0,\r\n");
      out.write("border_color:'#0000d3',\r\n");
      out.write("dn_css:'clsDayName',                        \r\n");
      out.write("cd_css:'clsCurrentDay',\r\n");
      out.write("wd_css:'clsWorkDay',\r\n");
      out.write("we_css:'clsWeekEnd',\r\n");
      out.write("wdom_css:'clsWorkDayOtherMonth',\r\n");
      out.write("weom_css:'clsWeekEndOtherMonth',\r\n");
      out.write("headerstyle: {\r\n");
      out.write("type:\"comboboxes\",\r\n");
      out.write("css:'clsWorkDayOtherMonth',\r\n");
      out.write("yearrange:[1987,2050]\r\n");
      out.write("},\r\n");
      out.write("monthnames :[\"January\", \"February\", \"March\", \"April\", \"May\", \"June\", \"July\", \"August\", \"September\", \"October\", \"November\", \"December\"],\r\n");
      out.write("daynames : [\"Su\", \"Mo\", \"Tu\", \"We\", \"Th\", \"Fr\", \"Sa\"]\r\n");
      out.write("};\r\n");
      out.write("var c1 = new CodeThatCalendar(caldef1);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function validateIndiaDate( strValue ) {\r\n");
      out.write("\tvar objRegExp = /^\\d{1,2}(\\-|\\/|\\.)\\d{1,2}\\1\\d{4}$/\r\n");
      out.write("\t//check to see if in correct format\r\n");
      out.write("\tif(!objRegExp.test(strValue))\r\n");
      out.write("\t    return false; //doesn't match pattern, bad date\r\n");
      out.write("\telse{\r\n");
      out.write("\t\tvar strSeparator = strValue.substring(2,3) //find date separator\r\n");
      out.write("\t    var arrayDate = strValue.split(strSeparator); //split date into month, day, year\r\n");
      out.write("\t    //create a lookup for months not equal to Feb.\r\n");
      out.write("\t    var arrayLookup = { '01' : 31,'03' : 31, '04' : 30,'05' : 31,'06' : 30,'07' : 31,\r\n");
      out.write("\t\t'08' : 31,'09' : 30,'10' : 31,'11' : 30,'12' : 31}\r\n");
      out.write("\t    var intDay = parseInt(arrayDate[0],10);\r\n");
      out.write("\t    //check if month value and day value agree\r\n");
      out.write("\t\tif(arrayLookup[arrayDate[1]] != null) {\r\n");
      out.write("\t      \tif(intDay <= arrayLookup[arrayDate[1]] && intDay != 0)\r\n");
      out.write("\t\t\t\treturn true; //found in lookup table, good date\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t  //check for February\r\n");
      out.write("\t  var intYear = parseInt(arrayDate[2],10);\r\n");
      out.write("\t  var intMonth = parseInt(arrayDate[1],10);\r\n");
      out.write("\t  if( ((intYear % 4 == 0 && intDay <= 29) || (intYear % 4 != 0 && intDay <=28)) && intDay !=0)\r\n");
      out.write("\t  \treturn true; //Feb. had valid number of days\r\n");
      out.write("\t  }\r\n");
      out.write("\t  return false; //any other values, bad date\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("#div1{\r\n");
      out.write("\tmargin: 1%; \r\n");
      out.write("\tborder: 1px solid black; \r\n");
      out.write("\twidth: 96%; \r\n");
      out.write("\tpadding-left: 1%; \r\n");
      out.write("\tpadding-right: 1%; \r\n");
      out.write("\theight: 280px;\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("\tbackground-color: #BEF781;\r\n");
      out.write("}\r\n");
      out.write("#div2{\r\n");
      out.write("\tborder: 1px solid black; \r\n");
      out.write("\tpadding: 1%; \r\n");
      out.write("\tmax-height: 550px;\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("\tbackground-color: #BEF781;\r\n");
      out.write("\tmargin-left: 0.3%;\r\n");
      out.write("\twidth: 97%;\"\r\n");
      out.write("}\r\n");
      out.write("#id11 tr:hover td{\r\n");
      out.write("background-color: #BEF781;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");

	String cust_code = request.getParameter("cust_code");
	String msg = request.getParameter("msg");
	ManagePayment manage = new ManagePayment("jdbc/js");
	manage.getCustInfo(cust_code);
	if(manage.rs.next()){

      out.write("\r\n");
      out.write("<center>\r\n");
      out.write("<table style=\"width: 95%; border-collapse: collapse; \" cellpadding=0 cellspacing=0>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td style=\"width: 30%;\" align=\"left\">\r\n");
      out.write("\t\t\t<div id=\"div1\" >\r\n");
      out.write("<Font size=\"3pt\" face=\"consolas\"><b> Customer Detail For Communication :</b></Font><br/>\r\n");
      out.write("<pre style=\"font-family: consolas;\"><b>Name    :</b>");
      out.print( manage.rs.getString(1) );
      out.write("  <b>Phone : </b> ");
      out.print( manage.rs.getString(9)+", "+ manage.rs.getString(10) );
      out.write("\r\n");
      out.write("<b>Address :</b>");
      out.print( manage.rs.getString(2)+" Building,"+manage.rs.getString(3)+" Block,");
      out.write("\r\n");
      out.write("         ");
      out.print(manage.rs.getString(4));
      out.print(" Wing," );
      out.print( manage.rs.getString(5)+","+manage.rs.getString(6));
      out.write("\r\n");
      out.write("         \r\n");
      out.write("<b>Station :</b>");
      out.print( manage.rs.getString(7) );
      out.write("</pre>\r\n");

	}
	manage.closeAll();

      out.write("\r\n");
      out.write("\t\t\t\t<form name=\"myform\" action=\"saveCommunication.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t<table style=\"width: 100%; border-collapse: collapse;\" cellpadding=0 cellspacing=0>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 30%; font-family: consolas;\" align=\"right\"> Subject :</td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 60%;\"><input type=\"text\" name=\"comm_subject\" style=\"width: 95%;\" id=\"comm_subject_id\" value=\"\"/></td>\r\n");
      out.write("\t\t\t\t\t\t<td rowspan=\"3\" style=\"width: 10%;\" valign=\"bottom\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" value=\"Save\" style=\"width: 100%;\" onclick=\" return validate()\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"reset\" value=\"Clear\"/>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 30%; font-family: consolas;\" valign=\"top\" align=\"right\"> Commit date :</td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 60%;\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type =\"text\" accesskey=\"d\" name=\"c_date\" size=\"15\" style=\"width: 79%;\" id=\"c_date_id\" readonly=\"readonly\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" onClick=\"c1.popup('c_date');\" value=\"...\" style=\"width: 15%;\"/>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 30%; font-family: consolas;\" valign=\"top\" align=\"right\"> Feedback :</td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 60%;\">\r\n");
      out.write("\t\t\t\t\t\t\t<textarea name=\"comm_feedback\" style=\"width: 95%;\" rows=\"3\" id=\"comm_feedback_id\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"cust_code\" value=\"");
      out.print(cust_code);
      out.write("\" id=\"cust_code_id\"/>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<br/>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td style=\"width: 35%;\" align=\"left\" >\r\n");
      out.write("\t\t\t<div id=\"div1\">\r\n");
      out.write("\t\t\t");

				ManagePayment manage1 =  new ManagePayment("jdbc/js");
				manage1.getCommHistory(cust_code);
				if(manage1.rs1.next()){
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<font size=\"3pt\" face=\"consolas\"><b>Communication History :</b></font>\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 100%; overflow-y:scroll;max-height: 60px;\">\r\n");
      out.write("\t\t\t\t\t\t<table style=\"width: 96%;float: right;\" border=1 cellpadding=0 cellspacing=0>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th style=\"width: 20%;\">Date</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th style=\"width: 15%;\">Con By</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th style=\"width: 20%;\">Commitment</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th style=\"width: 45%;\">Feedback</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 100%; overflow-y:scroll; max-height: 150px;\">\r\n");
      out.write("\t\t\t\t\t\t<table id=\"id11\" style=\"width: 96%;float: right; border-collapse: collapse;\" border=1 cellpadding=0 cellspacing=0>\r\n");
      out.write("\t\t\t\t\t");

					int cnt=0;
					do{
						if(cnt%2==0){
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr style=\"width: 100%;background-color:#ECFBB9;\">\r\n");
      out.write("\t\t\t\t\t\t");

						} else {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr style=\"width: 100%;background-color:#ECFB99;\">\r\n");
      out.write("\t\t\t\t\t\t");

						}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"width: 20%;\">");
      out.print(manage1.rs1.getDate(6) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"width: 15%;\">");
      out.print(manage1.rs1.getString(5) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"width: 20%;\">");
      out.print(manage1.rs1.getString(7));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"width: 45%;\">");
      out.print(manage1.rs1.getString(4) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t");
	
						cnt++;
					}while(manage1.rs1.next());
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t");

				}else{
					out.print("<h3> No Previous communication history</h3>");
				}
				manage1.closeAll();
			
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td style=\"width: 30%;\" align=\"left\" >\r\n");
      out.write("\t\t\t<div id=\"div1\">\r\n");
      out.write("\t\t\t");

			manage = new ManagePayment("jdbc/js");
			manage.getRecentPaymentDetail(cust_code);
			
      out.write("\r\n");
      out.write("\t\t\t<font size=\"3pt\" face=\"consolas\"><b>Payment History :</b></font>\r\n");
      out.write("\t\t\t<div style=\"width: 100%; overflow-y:scroll;max-height: 60px; overflow-x: hidden; \">\r\n");
      out.write("\t\t\t\t<table style=\"width: 96%;float: right;border-collapse: collapse;\" border=1 cellspacing=0 cellpadding=0>\r\n");
      out.write("\t\t\t\t\t<tr style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t\t\t<th style=\"width: 33%;\">Date</th>\r\n");
      out.write("\t\t\t\t\t\t<th style=\"width: 33%;\">Amount</th>\r\n");
      out.write("\t\t\t\t\t\t<th style=\"width: 33%;\">Rec By</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"width: 100%; overflow-y:scroll; max-height: 150px; overflow-x: hidden;\">\r\n");
      out.write("\t\t\t\t\t\t<table id=\"id11\" style=\"width: 96%;float: right; border-collapse: collapse;\" border=1 cellspacing=0 cellpadding=0>\r\n");
      out.write("\t\t\t");

			int count = 0;
			if(manage.rs.next()){
			do{
				if(count%2==0){
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr style=\"width: 100%;background-color:#ECFBB9;\">\r\n");
      out.write("\t\t\t\t\t");

					}else{
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr style=\"width: 100%;background-color:#ECFB99;\">\r\n");
      out.write("\t\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 33%;padding-left: 10px;\" align=\"left\" onclick=\"loaadDetailSinglePayment1('");
      out.print(manage.rs.getString(2));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print( manage.rs.getString(4) );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print( manage.rs.getString(7) );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print( manage.rs.getDate(6) );
      out.write("');\">\r\n");
      out.write("\t\t\t\t\t\t\t<font color=blue style=\"cursor: pointer;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<u>");
      out.print( manage.rs.getDate(6) );
      out.write("</u>\r\n");
      out.write("\t\t\t\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 33%;padding-left: 10px;\" align=\"left\">");
      out.print( manage.rs.getString(4) );
      out.write("&nbsp;Rs.</td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 33%;padding-left: 10px;\" align=\"left\">");
      out.print( manage.rs.getString(7) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t");

			count++;
			}while(manage.rs.next());
			}else{
			
      out.write("\r\n");
      out.write("\t\t\t<tr style=\"width: 100%;background-color:#ECFBB9;\"><td colspan=\"3\">No Previous Payment</td></tr>\r\n");
      out.write("\t\t\t");

			}
			
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");

			manage.closeAll();
			
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t<div id=\"div2\"></div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<div id=\"baseDiv\" style=\"top: 0px;\">\r\n");
      out.write("\t\t<div id=\"popupItemDiv\"\r\n");
      out.write("\t\t\tstyle=\"max-height: 400px; width: 60%; border: 2px solid black; background-color: #BEF781; \r\n");
      out.write("\t\t\t display: none; font-size: 100%; margin: 150px 0px 0px 250px;overflow-y: auto;\">\r\n");
      out.write("\t\t\t <div style=\"float: right; width: 20px;height: 20px; overflow: auto; cursor: pointer;\" onclick=\"funCloseDiv()\">\r\n");
      out.write("\t\t\t <img  src=\"images/close.png\"/>\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\t\t\t <div id=\"order_detail_popup\" style=\" width:100%; max-height: 89%;margin-top: 5%; overflow: auto; font: consolas;\"></div>\r\n");
      out.write("\t\t\t <br/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\twindow.onload = showHint('");
      out.print(cust_code);
      out.write("');\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
