/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-02-10 05:57:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.naming.*;
import javax.sql.*;
import java.text.*;
import java.io.*;

public final class DeliveryActionForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"ErrorPage.jsp?page=DeliveredActionForm.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

boolean flag1 = true;
try{
	if(request.getParameter("backPage").equals("ReceivePayment.jsp"))
		flag1 = false;
} catch (Exception e){
	System.out.print("Flag exp : ");
	//e.printStackTrace();
}
if(flag1){

      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t");

	session.getAttribute("UserName").toString();
	System.out.println("session bachka maapping : "+session +" \n user "+session.getAttribute("UserName").toString());
		
		
      out.write('\n');
      out.write('\n');

}

      out.write("\n");
      out.write("\n");
      out.write("<script src=\"js/lastOrderDetails.js\"></script>\n");

	String code,desc,status_code_value="TRANSIT",statusCode="",actionValue="";
	String[] actionValueArray=null;
  	String name="";
  	String custCode="";
  	String phno="";
  	String area="";
  	String add1="";
  	String add2="";
  	String orderNo="";
  	orderNo=request.getParameter("orderNo");
  	String orderDate="";
  	String status="";
  	String d_name="";
  	String d_code="";
  	String payment_type_desc="";
  	String totalItems="";
  	String deliveryBalance="";
  	float totalValue=0.0f;
  	float change=0.0f;
  	float balance=0.0f;
  	float advance=0.0f;
  	float discount=0.0f;
  	float paid_amt=0.0f;
  	float expected_amt=0.0f;
  	float other_charges=0.0f;
  	float sum = totalValue + change;
	float comm_amt=0.0f;
  	order.ManageOrder mo;
	mo = new order.ManageOrder("jdbc/js");
	mo.getOrderDetails(orderNo);
	
	while(mo.rs.next()){	
		custCode = mo.rs.getString("custcode");
	  	name = mo.rs.getString("custname");
	  	phno = mo.rs.getString("phone");
	  	area = mo.rs.getString("area");
	  	add1 = mo.rs.getString("add1");
	  	add2 = mo.rs.getString("add2");
	  	orderDate= mo.rs.getString("order_date");
	  	status= mo.rs.getString("status_code");
	  	d_name= mo.rs.getString("dstaff_name");
	  	d_code= mo.rs.getString("dstaff_code");
	  	totalItems= mo.rs.getString("total_items");
	  	totalValue=mo.rs.getFloat("total_value");
	 	change=mo.rs.getFloat("change_amt");
	  	balance = mo.rs.getFloat("balance_amt");
	  	advance = mo.rs.getFloat("advance_amt");
	  	discount = mo.rs.getFloat("discount_amt");
	 	sum = balance + change;
	 	payment_type_desc = mo.rs.getString("payment_type_desc");
	 	paid_amt = mo.rs.getFloat("paid_amt");
	 	expected_amt = mo.rs.getFloat("expected_amt");
	 	other_charges = mo.rs.getFloat("other_charges"); 
	 	comm_amt= mo.rs.getFloat("ord_comm_amt"); 	
	}
	mo.closeAll();


      out.write("\n");
      out.write("<form name=\"myform\" method=\"post\" class=\"ddm1\" id=\"form1\">\n");
      out.write("\t");

		if(flag1){
	
      out.write("\n");
      out.write("\t<br/>\n");
      out.write("\t<div style=\"border: 1px solid black; width: 90%;\">\n");
      out.write("\t");
}else{ 
      out.write("\n");
      out.write("\t<div style=\"display:none;\">\n");
      out.write("\t");
} 
      out.write("\n");
      out.write("\t<table  style=\" font-family: arial;\">\n");
      out.write("\t<tr align=\"left\">\n");
      out.write("    \t<th><font color=\"blue\">Current Status :</font></th>\n");
      out.write("    \t<th><label id='status' ></label></th>\n");
      out.write("    \t<td colspan=4></td>\n");
      out.write("    \t<th><font color=\"blue\">Next Action :</font></th>\n");
      out.write("    \t<th><label id='action' ></label></th>\n");
      out.write("    </tr>\n");
      out.write("\t</table>\n");
      out.write("\n");
      out.write("\t<table  style=\"width:100%; font-family: arial;\"> \n");
      out.write("\t\t<tr align=\"left\">\n");
      out.write("\t\t\t<td align=\"left\" valign=\"top\">\n");
      out.write("\t\t\t\t    \t\t<table id=\"1\" style=\"border: 1px solid black;width: 100%;\">\n");
      out.write("\t\t\t\t\t\t\t\t<tr><th colspan=\"5\" align=\"center\"><u>Customer Information</u></th></tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>Cust Code</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>: ");
      out.print(custCode);
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>Area</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>: ");
      out.print(area);
      out.write(" </td>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>Cust Name</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>: ");
      out.print(name);
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>Address 1</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>: ");
      out.print(add1);
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>Phone</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>: ");
      out.print(phno);
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>Address 2</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>: ");
      out.print(add2);
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th colspan=\"5\" align=\"center\"><hr></th>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th colspan=\"5\" align=\"center\"><u>Order Information</u></th>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr></tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>Order Num</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>: ");
      out.print(orderNo);
      out.write("</td>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>Order Date</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>: ");
      out.print(orderDate);
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>Total Items</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>: <label id='totalItem' ></label></td>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>Payment Type</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>: <label id='paymentdiv' ></label></td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>Total Value</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>: <label id='totalValue' ></label></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>Commission :</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td id=\"comm\">");
      out.print(comm_amt);
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td style=\"display: none;\"><input type=\"text\" name=\"comm1\" value=\"");
      out.print(comm_amt);
      out.write("\"/></td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>Less Discount</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>: ");
      out.print(discount);
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>Less Advance</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>: ");
      out.print(advance);
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>Balance</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									if(other_charges > 0){
									
      out.write("\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>: <font color=\"red\"><label id='balanceValue' ></label></font><font color=\"blue\">, Other Charges : ");
      out.print(other_charges);
      out.write("</font></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t");
			
									}else if(other_charges <=0){
									
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>: <font color=\"red\"><label id='balanceValue' ></label></font></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									}
									
      out.write("\t\n");
      out.write("\t\t\t\t\t\t\t\t\t<td></td>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>Change</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>: <label id='changeAmt' ></label></td>\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>Exp Amount </b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>: <label id='expamtdiv' ></label></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t\t\t\t<td><b>Paid Amount </b></td>\n");
      out.write("\t\t\t\t\t\t\t\t");

								if(payment_type_desc.equals("Cash") || payment_type_desc.equals("Cheque")){
								
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<td> :<input type=\"text\" name=\"paidamt\" size=\"5\" disabled value='");
      out.print(paid_amt);
      out.write("'></td>\n");
      out.write("\t\t\t\t\t\t\t\t");

								}else {
									if(flag1){
								
      out.write("\t\n");
      out.write("\t\t\t\t\t\t\t\t<td> :<input type=\"text\" name=\"paidamt\" size=\"5\" value='' ></td>\n");
      out.write("\t\t\t\t\t\t\t\t");
	
									} else{
								
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<td> :<input type=\"text\" name=\"paidamt\" size=\"5\" value='");
      out.print(other_charges);
      out.write("' ></td>\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
								}
								
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t<tr>\t\n");
      out.write("\t\t\t\t\t\t\t\t<td><b>Remark </b></td>\n");
      out.write("\t\t\t\t\t\t\t\t");

								if(flag1){
								
      out.write("\t\n");
      out.write("\t\t\t\t\t\t\t\t<td>:<input type=\"text\" name=\"remark\" size=\"20\" value='' ></td>\n");
      out.write("\t\t\t\t\t\t\t\t");

								} else{
								
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<td>:<input type=\"text\" name=\"remark\" size=\"20\" value=\"By receive Payment\" ></td>\n");
      out.write("\t\t\t\t\t\t\t\t");

								}
								if(payment_type_desc.equals("Credit") || payment_type_desc.equals("Hawala")){
								
      out.write("\t\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<td ><b>Cheque </b></td>\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<td ><input type=\"CHECKBOX\" name=\"chckchq\" value=''  onclick=\"SelectCheque();\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t");

								}
								
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t</tr>\t\n");
      out.write("\t\t\t\t\t\t\t");
	
								Connection conn=null;
								Statement stmt=null,stat=null;
								ResultSet rs=null,rs1=null;
								try {
									Context initContext = new InitialContext();
									Context envContext  = (Context)initContext.lookup("java:/comp/env");
									DataSource ds = (DataSource)envContext.lookup("jdbc/js");
									conn = ds.getConnection();
									stmt = conn.createStatement();	
									//stat = conn.createStatement();			
									rs = stmt.executeQuery("SELECT status_code, allow_action FROM status where status_code='"+status_code_value+"'");
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<tr>\t\n");
      out.write("\t\t\t\t\t\t\t\t<td><b>Del Person </b></td>\n");
      out.write("\t\t\t\t\t\t\t\t<td>: ");
      out.print(d_name);
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t\t\t\t<td><b>Allow Action </b></td>\n");
      out.write("\t\t\t\t\t\t\t\t<td>:<SELECT name=\"allow_action\" >\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<OPTION VALUE=\"\" >Select action</OPTION>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

										while(rs.next()){
											statusCode=rs.getString(1);
											actionValue=rs.getString(2);
										}
										actionValueArray=actionValue.split(",");
										for(int index=0; index<actionValueArray.length; index++){
											if(index==0 && !flag1){
												System.out.println(" index "+index+"\n actionValueArray "+actionValueArray[index]);
											
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<OPTION VALUE=\"");
      out.print( index);
      out.write("\" selected=\"selected\">");
      out.print( actionValueArray[index]);
      out.write("</OPTION>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

											} else{
												System.out.println(" index "+index+"\n actionValueArray "+actionValueArray[index]);
											
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<OPTION VALUE=\"");
      out.print( index);
      out.write('"');
      out.write('>');
      out.print( actionValueArray[index]);
      out.write("</OPTION>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

											}
										}
										
									    conn.close();
									    rs.close();
									    stmt.close();
									  }
									  catch (Exception e) {
									    conn.close();
									    rs.close();
									    stmt.close();
								        e.getMessage();
								        e.printStackTrace();
								      }    
									
      out.write("\t\t\n");
      out.write("\t\t\t\t\t\t\t\t</SELECT>\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t\t");

				if(flag1){
				
      out.write("\t\n");
      out.write("\t\t\t\t<td align=left valign=\"top\">\t\t\t\n");
      out.write("\t\t\t\t\t<div id=\"OrderHistory\" class=\"ddm1\"> </div> \n");
      out.write("\t\t\t\t</td>\t\t\n");
      out.write("\t\t\t\t");

				} else{
				
      out.write("\n");
      out.write("\t\t\t\t<td align=left valign=top>\t\t\t\n");
      out.write("\t\t\t\t\t<div id=\"OrderHistory\" class=\"ddm1\"  style=\"display:none;\"> </div> \n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t\t");

				}
				
      out.write("\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t</table>\t\t\n");
      out.write("\t</div>\n");
      out.write("\t<br/>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t<div id=\"txtHint\" class=\"ddm1\" style=\"background-color: white;\">\t</div>\n");
      out.write("\t<p><div id=\"waitMessage\"  style=\"cursor: sw-resize\"></div></p>\n");
      out.write(" \t<hr><br>\n");
      out.write(" \t<input type=\"hidden\" name=\"horderNo\" value=\"");
      out.print(orderNo);
      out.write("\">\n");
      out.write(" \t<input type=\"hidden\" name=\"horderDate\" value=\"");
      out.print(orderDate);
      out.write("\"> \t\n");
      out.write(" \t<input type=\"hidden\" name=\"hstatus\" value=\"");
      out.print(status);
      out.write("\">\n");
      out.write(" \t<input type=\"hidden\" name=\"d_staff\" value=\"");
      out.print(d_code);
      out.write("\">\n");
      out.write("\t<input type=\"hidden\" name=\"hsum\" value=\"");
      out.print(sum);
      out.write("\"> \t\n");
      out.write("\t<input type=\"hidden\" name=\"hicodearray\" value=\"\"> \t\n");
      out.write("\t<input type=\"hidden\" name=\"htotalitems\" value=\"");
      out.print(totalItems);
      out.write("\"> \n");
      out.write("\t<input type=\"hidden\" name=\"hretitem\" value=\"0\"> \t\n");
      out.write("\t<input type=\"hidden\" name=\"htotalvalue\" value=\"0\"> \n");
      out.write("\t<input type=\"hidden\" name=\"hitemtaken\" value=\"0\"> \n");
      out.write("\t<input type=\"hidden\" name=\"hretmrp\" value=\"0\"> \n");
      out.write("\t<input type=\"hidden\" name=\"hpagename\" value=\"DeliveryActionForm\"> \n");
      out.write("\t<input type=\"hidden\" name=\"hchange\" value=\"");
      out.print(change);
      out.write("\"> \t\t\t\t\t\n");
      out.write("\t<input type=\"hidden\" name=\"hsplitflag\" value=\"0\"> \t\t\n");
      out.write("\t<input type=\"hidden\" name=\"hallowaction\" value=\"\">\t\n");
      out.write("\t<input type=\"hidden\" name=\"hafterretcomm\" value=\"0\">\t\n");
      out.write("\t<input type=\"hidden\" name=\"hCheckChanged\" value=\"No\">\n");
      out.write("\t<input type=\"hidden\" name=\"htotalmrp\" value=\"0\">\n");
      out.write("\t<input type=\"hidden\" name=\"holdItems\" value=\"\">\n");
      out.write("\t");
if(flag1){ 
      out.write("\n");
      out.write("\t<input type=\"hidden\" name=\"hbalanceAmt\" value=\"");
      out.print(expected_amt);
      out.write("\">\n");
      out.write("\t<input type=\"hidden\" name=\"back_page\" value=\"TrackingForm.jsp\">\n");
      out.write("\t<input type=\"hidden\" name=\"cust_code\" value=\"\">\n");
      out.write("\t");
}else{
	
      out.write("\n");
      out.write("\t<input type=\"hidden\" name=\"hbalanceAmt\" value=\"");
      out.print(expected_amt - change);
      out.write("\">\n");
      out.write("\t<input type=\"hidden\" name=\"back_page\" value=\"");
      out.print(request.getParameter("backPage"));
      out.write("\">\n");
      out.write("\t<input type=\"hidden\" name=\"cust_code\" value=\"");
      out.print(request.getParameter("cust_code"));
      out.write("\">\n");
      out.write("\t");

	} 
      out.write("\n");
      out.write("\t<input type=\"hidden\" name=\"hpaid_amt\" value=\"0\">\n");
      out.write("\t\n");
      out.write("\t<input type=\"hidden\" name=\"hqtyArray\" value=\"0\">\n");
      out.write("\t<input type=\"hidden\" name=\"hpriceArray\" value=\"0\">\n");
      out.write("\t<input type=\"hidden\" name=\"hentryArray\" value=\"0\">\n");
      out.write("\t<input type=\"submit\" name=\"Submit\"  disabled accesskey=\"s\" onClick=\" checkField();return false; \" value=\"Save <Alt+s>\"/>\n");

	if(flag1){
	
      out.write("\n");
      out.write("\t<input type=\"reset\" name=\"clear\" accesskey=\"r\" value=\"Clear <Alt+r>\">\n");
      out.write("\t<INPUT type=BUTTON value=\"Cancel <Alt+c>\" accesskey=\"c\" onClick=\"showMsg();\"></center>\n");
      out.write("\t");

	}else{
	
      out.write("\n");
      out.write("\t<INPUT type=BUTTON  accesskey=\"c\" onClick=\"javascript:window.location ='");
      out.print( request.getParameter("backPage"));
      out.write("?cust_code=");
      out.print(request.getParameter("cust_code"));
      out.write("'\" value=\"Cancel <Alt+c>\">\n");
      out.write("\t");
} 
      out.write("\n");
      out.write("\t\n");
      out.write("</form>\n");
      out.write("<script type=\"text/javascript\">\t\n");
      out.write("\t\t//document.myform.paidamt.focus();\t\n");
      out.write("\t\tif(\"");
      out.print(payment_type_desc);
      out.write("\"=='Credit' || \"");
      out.print(payment_type_desc);
      out.write("\"=='Hawala')\n");
      out.write("\t\t\tdocument.myform.paidamt.focus();\n");
      out.write("\t\tdocument.onkeydown = checkKey;\n");
      out.write("\t\tdocument.onclick = checkKey;\n");
      out.write("\t\tfunction checkKey() {\n");
      out.write("\t\t\tdocument.myform.Submit.disabled=false;\t\t\t\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction checkField(){\t\n");
      out.write("\t\t\t//alert(\"submit \") \n");
      out.write("\t\t\t\n");
      out.write("\t\t\tcheckreturnedItem();\n");
      out.write("\t\t\t\n");
      out.write("\t\t\ttemp=document.myform.hicodearray.value.split(',');\t\t\t\n");
      out.write("\t\t\tvar paidamt  = document.myform.paidamt.value;\t\n");
      out.write("\t\t\tvar allow_action = document.myform.allow_action.value;\t\n");
      out.write("\t\t\tvar allow_actionnm = document.myform.allow_action[document.myform.allow_action.selectedIndex].text;\t\t\t\t\n");
      out.write("\t\t\tdocument.myform.hallowaction.value=allow_actionnm;\t\n");
      out.write("\t\t\tdocument.myform.hafterretcomm.value=document.getElementById(\"comm\").innerHTML;\n");
      out.write("\t\t\tdocument.myform.htotalmrp.value = document.getElementById(\"totMrp\").innerHTML;\n");
      out.write("\t\t\tdocument.myform.hchange.value=document.getElementById(\"changeAmt\").innerHTML;\n");
      out.write("\t\t\tdocument.myform.hbalanceAmt.value=document.getElementById(\"balanceValue\").innerHTML;\n");
      out.write("\t\t\t//document.myform.hexpectedAmt.value=document.getElementById(\"expamtdiv\").innerHTML;\t\t\t\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tvar remark  = document.myform.remark.value;\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tif(paidamt==\"\"){//} && allow_actionnm==\"Delivery Done\") {\n");
      out.write("\t\t\t\t\talert(\"Please Enter Paid Amount \");\n");
      out.write("\t\t\t\t\tdocument.myform.paidamt.focus();\n");
      out.write("\t\t\t\t\treturn false;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\telse if(paidamt>parseFloat(document.getElementById(\"expamtdiv\").innerHTML)) \n");
      out.write("\t\t\t\talert(\"Paid amount should not be greater than expected amount\");\t\t\t\n");
      out.write("/*\t\t\t\n");
      out.write("\t\t\telse if(parseInt(document.getElementById(\"totalItem\").innerHTML)<=0)\n");
      out.write("\t\t\t\talert(\"Order with zero items cannot be delivered\");\t\n");
      out.write("*/\t\t\n");
      out.write("\t\t\telse if(allow_action==\"\") {\n");
      out.write("\t\t\t\t\talert(\"Please Select Allow action\");\n");
      out.write("\t\t\t\t\tdocument.myform.allow_action.focus();\n");
      out.write("\t\t\t\t\treturn false;\n");
      out.write("\t\t\t}\t\n");
      out.write("\n");
      out.write("\t\t\telse if(isNaN(paidamt)) {\n");
      out.write("\t\t\t\talert(\"Please Enter a number in Pai amount field\");\n");
      out.write("\t\t\t\tdocument.myform.paidamt.value=\"\";\n");
      out.write("\t\t\t\tdocument.myform.paidamt.focus();\n");
      out.write("\t\t\t\treturn false;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t//else if(paidamt != ");
      out.print(sum);
      out.write("){\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\telse if(parseFloat(paidamt) != parseFloat(document.getElementById(\"expamtdiv\").innerHTML)){\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\tif(remark==''&& allow_actionnm==\"Delivery Done\")\n");
      out.write("\t\t\t\t\talert(\"Please fill the remark field\");\t\t\t\t\t\n");
      out.write("\t\t\t\telse if(remark!='' && allow_actionnm==\"Delivery Done\"){\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\tvar ans=confirm(\"The paid amount is \"+ paidamt +\" instead of \"+document.getElementById(\"expamtdiv\").innerHTML +\". Do you still want to change the status to Delivered? \");\t\t\t\t\t\n");
      out.write("\t\t\t\t\tif (ans==true ){\n");
      out.write("\t\t\t\t\t\tvar str=\"\";\n");
      out.write("\t\t\t\t\t\tif(\"");
      out.print(payment_type_desc);
      out.write("\"=='Credit' || \"");
      out.print(payment_type_desc);
      out.write("\"=='Hawala')\n");
      out.write("\t\t\t\t\t\t\tdocument.myform.paidamt.disabled=false;\t\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\tdocument.myform.action=\"DeliveryAction.jsp\";\n");
      out.write("\t\t\t\t\t\tdocument.myform.submit();\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\telse{\n");
      out.write("\t\t\t\t\t  \twindow.refresh; \n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\telse if(remark!='' || allow_actionnm==\"Hold\"){\t\t\t\t\n");
      out.write("\t\t\t\t\tvar ans=confirm(\"The paid amount is \"+ paidamt +\" instead of \"+ document.getElementById(\"expamtdiv\").innerHTML+\". Do you still want to change the status to Hold? \");\t\t\t\t\t\n");
      out.write("\t\t\t\t\tif (ans==true ){\n");
      out.write("\t\t\t\t\t\tvar str=\"\";\n");
      out.write("\t\t\t\t\t\tif(\"");
      out.print(payment_type_desc);
      out.write("\"=='Credit' || \"");
      out.print(payment_type_desc);
      out.write("\"=='Hawala' || \"");
      out.print(payment_type_desc);
      out.write("\"=='Cheque')\n");
      out.write("\t\t\t\t\t\t\tdocument.myform.paidamt.disabled=false;\t\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\tdocument.myform.action=\"DeliveryAction.jsp\";\n");
      out.write("\t\t\t\t\t\tdocument.myform.submit();\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\telse{\n");
      out.write("\t\t\t\t\t  \twindow.refresh; \n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t}\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\telse{\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\tvar ans=confirm(\"Do you want to change the status to Delivered? \");\n");
      out.write("\t\t\t\tif (ans==true){\n");
      out.write("\t\t\t\t\t//checkreturnedItem();\n");
      out.write("\t\t\t\t\tif(\"");
      out.print(payment_type_desc);
      out.write("\"=='Credit' || \"");
      out.print(payment_type_desc);
      out.write("\"=='Hawala')\n");
      out.write("\t\t\t\t\t\tdocument.myform.paidamt.disabled=false;\t\t\n");
      out.write("\t\t\t\t\tdocument.myform.action=\"DeliveryAction.jsp\";\n");
      out.write("\t\t\t\t\tdocument.myform.submit();\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\telse{\n");
      out.write("\t\t\t\t  \twindow.refresh; \n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction showMsg(){\n");
      out.write("\t\t  \t document.myform.action=\"TrackingForm.jsp\";\n");
      out.write("\t\t   \t document.myform.submit();\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction func(){\t\n");
      out.write("\t\t\tdocument.getElementById(\"totalItem\").innerHTML=\"");
      out.print(totalItems);
      out.write("\";\n");
      out.write("\t\t\tdocument.getElementById(\"totalValue\").innerHTML=\"");
      out.print(totalValue);
      out.write("\";\n");
      out.write("\t\t\tdocument.getElementById(\"expamtdiv\").innerHTML=");
      out.print(expected_amt);
      out.write(";\n");
      out.write("\t\t\tdocument.getElementById(\"changeAmt\").innerHTML=");
      out.print(change);
      out.write(";\n");
      out.write("\t\t\tdocument.getElementById(\"status\").innerHTML=\"");
      out.print(status);
      out.write("\";\n");
      out.write("\t\t\tdocument.getElementById(\"action\").innerHTML=\"");
      out.print(actionValue);
      out.write("\";\n");
      out.write("\t\t\tdocument.getElementById(\"paymentdiv\").innerHTML=\"");
      out.print(payment_type_desc);
      out.write("\";\n");
      out.write("\t\t\tdocument.getElementById(\"balanceValue\").innerHTML=\"");
      out.print(balance);
      out.write("\";\n");
      out.write("\t\t\tbalanceValue\n");
      out.write("\t\t\tif(\"");
      out.print(payment_type_desc);
      out.write("\"=='Credit' || \"");
      out.print(payment_type_desc);
      out.write("\"=='Hawala')\n");
      out.write("\t\t\t\tdocument.myform.chckchq.checked=false;\n");
      out.write("\t\t\tshowHistory();\n");
      out.write("\t\t\t//showHint(document.myform.hpagename.value);\n");
      out.write("\t\t\t\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction SelectCheque(){\n");
      out.write("\t\t\tif(document.myform.chckchq.checked==true){\n");
      out.write("\t\t\t\tdocument.getElementById(\"paymentdiv\").innerHTML='Cheque';\n");
      out.write("\t\t\t\tdocument.myform.hCheckChanged.value='Yes';\n");
      out.write("\t\t\t\tdocument.myform.paidamt.disabled=\"disabled\";\n");
      out.write("\t\t\t\tdocument.myform.paidamt.value=document.getElementById(\"expamtdiv\").innerHTML;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\telse if(document.myform.chckchq.checked==false){\n");
      out.write("\t\t\t\tdocument.getElementById(\"paymentdiv\").innerHTML=\"");
      out.print(payment_type_desc);
      out.write("\";\n");
      out.write("\t\t\t\tdocument.myform.hCheckChanged.value='No';\n");
      out.write("\t\t\t\tdocument.myform.paidamt.value='';\n");
      out.write("\t\t\t\tdocument.myform.paidamt.disabled=\"\";\n");
      out.write("\t\t\t\tdocument.myform.paidamt.focus();\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\twindow.onload= func;\n");
      out.write("   \t</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
