/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-02-07 09:33:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.naming.*;
import javax.sql.*;

public final class EditUser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"ErrorPage.jsp?page=EditUser.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\n");
      out.write("\t");

	session.getAttribute("UserName").toString();
	//System.out.println("session bachka maapping : "+session +" \n user "+session.getAttribute("UserName").toString());
	
      out.write('\n');
      out.write('\n');
      out.write('\n');

	Connection conn=null,conn1=null;
	Statement stmt=null,stmt1=null;
	ResultSet rs=null,rs1=null;
	if (request.getParameter("nameStartWith") != null){
    	try {
			Context initContext = new InitialContext();
			Context envContext  = (Context)initContext.lookup("java:/comp/env");
			DataSource ds = (DataSource)envContext.lookup("jdbc/js");
			conn = ds.getConnection();
			stmt = conn.createStatement();
			String selSql = "select * from user";
			selSql=selSql + " where username='"+request.getParameter("nameStartWith")+"'";
			rs = stmt.executeQuery(selSql);
			while(rs.next()){

      out.write("\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<table>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td align=\"left\"><b>User Name</b></td><td>: </td>\n");
      out.write("\t\t\t    \t<td><input name=\"userName\" id=\"userName\"  type=\"text\" maxlength=\"20\" value=\"");
      out.print(rs.getString(1));
      out.write("\" readonly  onClick=\"Warn();\"><br></td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr></tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t  <td align=\"left\"><b><font color=\"blue\">P</font>assword</td><td>: </td>\n");
      out.write("\t\t\t    \t<td><input name=\"userPasswd\" id=\"userPasswd\"  accesskey=\"p\" type=\"password\"  maxlength=\"20\" value=\"");
      out.print(rs.getString(2));
      out.write("\" ><br></td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr></tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td align=\"left\"><b><font color=\"blue\">T</font>ype Of User</td><td>: </td>\n");
 
						try {
							String name,desc;
						  	int rowcount;
							Context initContext1 = new InitialContext();
							Context envContext1  = (Context)initContext1.lookup("java:/comp/env");
							DataSource ds1 = (DataSource)envContext1.lookup("jdbc/js");
							conn1 = ds1.getConnection();
							stmt1 = conn1.createStatement();
				          	rs1 = stmt1.executeQuery("select user_type_code, user_type_desc from user_type");

      out.write("\n");
      out.write("\t\t\t\t\t\t\t<td align=\"left\">\n");
      out.write("\t\t\t\t\t\t\t<SELECT name=\"userType\" style=\"width:11em\">\n");
 							
			 				while (rs1.next()) {
				 				name = rs1.getString(1);
						    	desc = rs1.getString(2);
						    	if(name.equals(rs.getString(5))){			 				
				 				

      out.write("\n");
      out.write("\t\n");
      out.write(" \t\t\t\t\t\t\t\t\t<OPTION VALUE=\"");
      out.print(name);
      out.write("\" selected >");
      out.print(desc);
      out.write("</OPTION>\n");
 
								}
								else {

      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<OPTION VALUE=\"");
      out.print(name);
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(desc);
      out.write("</OPTION>\n");

								} 
							
								
							}	
						   
					   		rs1.close();
					    	stmt1.close();
					    	conn1.close();
						}
						catch (Exception e) {
			        		e.getMessage();
			            	e.printStackTrace();
			            	rs1.close();
					    	stmt1.close();
					    	conn1.close();
			          	}

      out.write("\n");
      out.write("\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t</td>\t\t\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr></tr>   \n");
      out.write("\t\t\t    <tr>\n");
      out.write("\t\t\t\t\t<td align=\"left\"><b><font color=\"blue\">E</font>mail Id</td><td>: </td>\n");
      out.write("\t\t\t  \t\t<td><input name=\"eEmail\" id=\"eEmail\" type=\"text\" maxlength=40 value=\"");
      out.print(rs.getString(7));
      out.write("\" accesskey=\"e\"><br></td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr></tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td align=\"left\"><b><font color=\"blue\">C</font>ontact No</td><td>: </td>\n");
      out.write("\t\t\t    \t<td><input name=\"contactNo\" id='contactNo' type=\"text\" size=20 maxlength=20 value=\"");
      out.print(rs.getString(8));
      out.write("\" accesskey=\"c\"><br></td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t</table><br><br>\n");
      out.write("\t\t\t<center><INPUT type=\"submit\" name=\"Submit\" value=\"Update <Alt+u>\" accesskey=\"u\" disabled  onClick=\"Operation1();\">&nbsp;&nbsp;&nbsp;\n");
      out.write("\t        <INPUT type=\"button\" value=\"Delete <Alt+d>\" accesskey=\"d\" onClick=\"Operation2();\">&nbsp;&nbsp;&nbsp;\n");
      out.write("\t        <INPUT type=\"reset\" value=\"Reset <Alt+r>\" accesskey=\"r\">&nbsp;&nbsp;&nbsp;\n");
      out.write("\t        <INPUT type=\"button\" value=\"Cancel <Alt+c>\" accesskey=\"c\" onClick=\"showMsg();\"></center>\n");
      out.write("\t      \n");
      out.write("\n");
      out.write("\t\t\t\n");

			}         
	  		rs.close();
	  		stmt.close();
	  		conn.close();
		}
		catch (Exception e) {
			e.getMessage();
			e.printStackTrace();
			rs.close();
	  		stmt.close();
	  		conn.close();
		}
	}

      out.write('\n');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
