/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-02-11 11:56:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class EditVendorForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"ErrorPage.jsp?page=EditVendorForm.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\n");
      out.write("\t");

	session.getAttribute("UserName").toString();
	//System.out.println("session bachka maapping : "+session +" \n user "+session.getAttribute("UserName").toString());
	
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"js/vendor.js\"></script> \n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/border_radius.css\" />\n");
      out.write("<form name=\"myform\" >\n");
      out.write("\n");

	int vendorId = Integer.parseInt(request.getParameter("vendorId"));
	String vendorName = request.getParameter("vendorName");
	String vendorAddress = request.getParameter("vendorAddress");
	if(vendorAddress == null){
		vendorAddress = "";
	}
	String vendorPhone = request.getParameter("vendorPhone");
	if(vendorPhone == null){
		vendorPhone = "";
	}

      out.write("\n");
      out.write("<fieldset style=\"width: 40%;\">\n");
      out.write("<legend><h3 align=\"center\">Edit Vendor</h3></legend>\n");
      out.write("<table align=\"center\">\n");
      out.write("\t<tr>\n");
      out.write("\t\t<td align=\"left\" style=\"width: 30%;\"><b>Vendor <font color=\"blue\"><u>N</u></font>ame</b></td>\n");
      out.write("\t\t<td>:</td>\n");
      out.write("\t\t<td><input type=\"text\" name=\"vendorName\" accesskey=\"n\" value=\"");
      out.print(vendorName);
      out.write("\" style=\"width: 100%;\"/></td>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr>\n");
      out.write("\t\t<td align=\"left\"><b><font color=\"blue\"><u>P</u></font>hone Number </b></td>\n");
      out.write("\t\t<td>:</td>\n");
      out.write("\t\t<td><input type=\"text\" name=\"vendorPhone\" accesskey=\"p\" value=\"");
      out.print(vendorPhone);
      out.write("\" style=\"width: 100%;\"/></td>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr>\n");
      out.write("\t\t<td align=\"left\"><b><font color=\"blue\"><u>V</u></font>endor Address</b></td>\n");
      out.write("\t\t<td>:</td>\n");
      out.write("\t\t<td><input type=\"text\" name=\"vendorAddress\" rows=\"3\" accesskey=\"v\" size=\"40\" value=\"");
      out.print(vendorAddress);
      out.write("\" style=\"width: 100%;\"/></td>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr><td>&nbsp;</td></tr>\n");
      out.write("\t<tr>\n");
      out.write("\t\t<td colspan=\"3\">\n");
      out.write("\t\t<input type=\"hidden\" name=\"vendorId\" value=\"");
      out.print(vendorId);
      out.write("\" />\n");
      out.write("\t\t\t<input type=\"button\" accesskey=\"s\" value=\"Update Vendor<Alt+s>\" onclick=\"funUpdate();\"/>\n");
      out.write("\t\t\t<input type=\"reset\" accesskey=\"c\" value=\"Clear<Alt+c>\"/>\n");
      out.write("\t\t\t<input type=\"button\" accesskey=\"h\" value=\"Home<Alt+h>\" onclick=\"funCancel();\"/>\n");
      out.write("\t\t</td>\n");
      out.write("\t</tr>\n");
      out.write("</table>\n");
      out.write("</fieldset>\n");
      out.write("</form>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
