/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-02-11 10:20:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.naming.*;
import javax.sql.*;
import java.io.*;
import java.text.*;

public final class editItemDetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "sessionBoth.jsp" + (("sessionBoth.jsp").indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("formName", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("editItemDetails.jsp", request.getCharacterEncoding()), out, false);
      out.write(" \n");
      out.write("\n");
      out.write("\n");

	int site_id=0;
	DecimalFormat df = new DecimalFormat("###,###.00");
	try{
		site_id = (Integer)session.getAttribute("GlobalSiteId");
		System.out.print("In : "+site_id);
	}catch(Exception e){
		e.printStackTrace();
	}
	String i_code="";
	String ig_code="";
	String i_name="";
	String i_mrp="";
	String i_mrp2="";
	String i_rate="";
	String i_rate2="";	
	String flag="";
	String paramList="";
	String changeParamList="";
	String i_tickflag="";
	String ibarcode = request.getParameter("ibarcode");
	i_code=request.getParameter("icodeStartWith");
	ig_code=request.getParameter("igcodeStartWith");
	
	i_name=request.getParameter("inameStartWith");
	i_mrp=request.getParameter("imrpStartWith");
	i_rate=request.getParameter("irateStartWith");
	i_mrp2=request.getParameter("imrp2StartWith");
	i_rate2=request.getParameter("irate2StartWith");
	flag=request.getParameter("flag");		
	i_tickflag = request.getParameter("i_tickflg");
	
	
	item.ManageItem mi;
	mi = new item.ManageItem("jdbc/js");
    	
    mi.listItem(i_code,ig_code,i_name,i_mrp,i_mrp2,i_rate,i_rate2,i_tickflag,ibarcode,site_id);
    	
		

      out.write("\n");
      out.write("       <style>\n");
      out.write("       #id #tr:hover td{\n");
      out.write("       \t\tbackground-color: white;\n");
      out.write("       \t\tcursor: pointer;\n");
      out.write("       }\n");
      out.write("       #id td{\n");
      out.write("       \t\tpadding: 3px 0px 3px 5px;\n");
      out.write("       }\n");
      out.write("       </style>\n");
      out.write("       <table border=\"1\" name=\"t\" id=\"id\" class=\"item3\" cellspacing = 0 cellpadding = 0 style=\"border-collapse: collapse; width: 96%;background-color: #ECFB99;\" bordercolor=black>\n");
      out.write("      \n");
      out.write("    \t <thead>\n");
      out.write("     \t\t  \t<tr align=\"left\">\n");
      out.write("\t\t\t\t<td><b>Item Code</b></td>\n");
      out.write("\t\t\t\t<td><b>Change Quantity</b></td>\n");
      out.write("\t\t\t\t<td><b>Item Group</b></td>\n");
      out.write("\t\t\t\t<td><b>Item  Name</b></td>\n");
      out.write("\t\t\t\t<td><b>Item  Barcode</b></td>\n");
      out.write("\t\t\t\t<td><b>Item Weight</b></td>\n");
      out.write("\t\t\t\t<td><b>Item MRP</b></td>\n");
      out.write("\t\t\t\t<td><b>Item Rate</b></td>\n");
      out.write("\t\t\t\t<td><b>Deal Flag</b></td>\n");
      out.write("\t\t\t\t<td><b>Ticker Flag</b></td>\n");
      out.write("\t\t\t\t<td><b>Is bachka</b></td>\n");
      out.write("\t\t\t\t<td><b>Mix Item</b></td>\n");
      out.write("\t\t\t\t<td><b>Item History</b></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("     \t</thead>\t\n");
      out.write("\t\t<tbody>\n");
		
	       
	      	while(mi.rs.next()) {
	      	if(flag.equals("1")){
	       		paramList="EditItemForm.jsp?icode="+mi.rs.getString(1)+"&igcode="+mi.rs.getString(7)+"&iname="+mi.rs.getString(3)+"&iweight="+mi.rs.getString(4)+"&imrp="+mi.rs.getString(5)+"&irate="+mi.rs.getString(6)+"&id_type="+mi.rs.getString(10)+"&id_flag="+mi.rs.getString(9)+"&id_qty="+mi.rs.getString(11)+"&id_amt="+mi.rs.getString(12)+"&i_comm="+mi.rs.getString(13)+"&i_tickflag="+mi.rs.getString(14)+"&ibarcode="+mi.rs.getString(15)+"&box_qty="+mi.rs.getInt(16)+"&is_bachka="+mi.rs.getString("is_bachka")+"&is_mixture="+mi.rs.getString("mix_item")+"&groupCodeValue="+mi.rs.getString("item_group_code");	       			
	       }
	       else{
	       		paramList="ItemDetails.jsp?icode="+mi.rs.getString(1)+"&igcode="+mi.rs.getString(7)+"&iname="+mi.rs.getString(3)+"&iweight="+mi.rs.getString(4)+"&imrp="+mi.rs.getString(5);		
	       }
	      	changeParamList="ChangeQuantityItemForm.jsp?icode="+mi.rs.getString(1)+"&igcode="+mi.rs.getString(7)+"&iname="+mi.rs.getString(3)+"&iweight="+mi.rs.getString(4)+"&imrp="+mi.rs.getString(5)+"&irate="+mi.rs.getString(6)+"&id_type="+mi.rs.getString(10)+"&id_flag="+mi.rs.getString(9)+"&id_qty="+mi.rs.getString(11)+"&id_amt="+mi.rs.getString(12)+"&i_comm="+mi.rs.getString(13)+"&i_tickflag="+mi.rs.getString(14)+"&ibarcode="+mi.rs.getString(15);
	       	
	        
      out.write("\n");
      out.write("\t\t\t  <tr id=\"tr\" align=\"left\">\t\t\n");
      out.write("\t\t\t\t<td align=\"left\"><a  href=\"");
      out.print(paramList);
      out.write('"');
      out.write('>');
      out.print(mi.rs.getString(1));
      out.write("</a></td>\n");
      out.write("    \t \t\t<td><a href=\"");
      out.print(changeParamList);
      out.write("\">Change Quantity</a></td>\n");
      out.write("    \t \t\t<td>");
      out.print(mi.rs.getString(7));
      out.write("</td>\n");
      out.write("    \t \t\t<td>");
      out.print(mi.rs.getString(3));
      out.write("</td>\n");
      out.write("    \t \t\t<td>");
      out.print(mi.rs.getString(15));
      out.write("</td>\n");
      out.write("    \t \t\t<td>");
      out.print(mi.rs.getString(4));
      out.write("</td>\n");
      out.write("    \t \t\t<td>");
      out.print(df.format(mi.rs.getFloat(5)));
      out.write("</td>\n");
      out.write("    \t \t\t<td>");
      out.print(df.format(mi.rs.getFloat(6)));
      out.write("</td>\n");
      out.write("    \t \t\t");
      out.write("\n");
      out.write("    \t \t\t<td>\n");
	
                String msg1= mi.rs.getString(9); 
                if(msg1.equals("N")){   
           			out.println("No");
           		}
           		else{
           			out.println("Yes");
           		}

      out.write("  \n");
      out.write("          \t\t</td><td>\n");
	
                String msg2= mi.rs.getString(14); 
                if(msg2.equals("N")){   
           			out.println("No");
           		}
           		else{
           			out.println("Yes");
           		}

      out.write("  \n");
      out.write("            \t</td>\n");
      out.write("            \t<td>");
      out.print(mi.rs.getString("is_bachka") );
      out.write("</td>\n");
      out.write("            \t<td>");
      out.print(mi.rs.getString("mix_item") );
      out.write("</td><td> \n");
          	
                String msg= mi.rs.getString(8); 
                if(!msg.equals("NH")){                      

      out.write("                       \n");
      out.write("            \t    <a  href=\"ItemHistoryForm.jsp?icode=");
      out.print(mi.rs.getString(1));
      out.write("\">history\n");
           
                }

      out.write("\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("            \t \n");
      out.write("\t\t\t    </td></tr>\n");
      out.write("\t\t\t\n");
			    
		      }
		      mi.closeAll();			  

      out.write("\n");
      out.write("\t\t\t <style type=\"text/css\">\n");
      out.write("\t\t\t a:link {color: blue}\n");
      out.write("\t\t\t a:hover {background: blue;color: white}\n");
      out.write("\t\t\t a:active {background: blue;color: white}\n");
      out.write("\t\t\t </style>\n");
      out.write("\n");
      out.write("\t</tbody>\n");
      out.write("</table>\n");
      out.write("\t\t\t\n");
      out.write("    \t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
