/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-02-24 11:02:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.naming.*;
import javax.sql.*;
import java.io.*;

public final class editCustomerForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"ErrorPage.jsp?page=editCustomerForm.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write(' ');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\t\n");
      out.write("\t");

	session.getAttribute("UserName").toString();
	//System.out.println("session bachka maapping : "+session +" \n user "+session.getAttribute("UserName").toString());
	
      out.write("\n");
      out.write(" \n");
      out.write("\n");
      out.write("<script type=\"text/javascript\"  src=\"js/customerOrderDetails.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"js/codethatcalendarstd.js\"></script>\n");
      out.write("<style>\n");
      out.write("hr {\n");
      out.write("color: #f00;\n");
      out.write("background-color: #f00;\n");
      out.write("height: 3px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");

		String customerName="";
	  	customerName=request.getParameter("name");
	  	String telephone="";
	  	telephone=request.getParameter("tele");
	  	String building="";
	  	building=request.getParameter("bldg");
	  	String building_no="";
	  	building_no=request.getParameter("building_no");
	  	String block="";
	  	block=request.getParameter("block");
		String wing="";
	 	wing=request.getParameter("wing");
		String add1="";
	 	add1=request.getParameter("add1");
	 	String add2="";
		add2=request.getParameter("add2");
		String custCode="";
		custCode=request.getParameter("cuscode");
		String area="";
	    area=request.getParameter("area");
	    String station="";
		station=request.getParameter("station");
	    String pincode="";
		pincode=request.getParameter("pincode");
		String city="";
		city=request.getParameter("city");
		String state="";
		state=request.getParameter("state");
		String payment = request.getParameter("payment");
		String mobile = request.getParameter("mobile");
					

      out.write("  \n");
      out.write("\t\t\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tvar caldef1 = {\n");
      out.write("\tfirstday:0,\n");
      out.write("\tdtype:'dd/MM/yyyy',\n");
      out.write("\twidth:250,\n");
      out.write("\twindoww:300,\n");
      out.write("\twindowh:200,\n");
      out.write("\tborder_width:0,\n");
      out.write("\tborder_color:'#0000d3',\n");
      out.write("\tdn_css:'clsDayName',                        \n");
      out.write("\tcd_css:'clsCurrentDay',\n");
      out.write("\twd_css:'clsWorkDay',\n");
      out.write("\twe_css:'clsWeekEnd',\n");
      out.write("\twdom_css:'clsWorkDayOtherMonth',\n");
      out.write("\tweom_css:'clsWeekEndOtherMonth',\n");
      out.write("\theaderstyle: {\n");
      out.write("\ttype:\"comboboxes\",\n");
      out.write("\tcss:'clsWorkDayOtherMonth',\n");
      out.write("\tyearrange:[1940,2050]\n");
      out.write("\t},\n");
      out.write("\tmonthnames :[\"January\", \"February\", \"March\", \"April\", \"May\", \"June\", \"July\", \"August\", \"September\", \"October\", \"November\", \"December\"],\n");
      out.write("\tdaynames : [\"Su\", \"Mo\", \"Tu\", \"We\", \"Th\", \"Fr\", \"Sa\"]\n");
      out.write("\t};\n");
      out.write("\tvar c1 = new CodeThatCalendar(caldef1);\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\tfunction validateIndiaDate( strValue ) {\n");
      out.write("\t\tvar objRegExp = /^\\d{1,2}(\\-|\\/|\\.)\\d{1,2}\\1\\d{4}$/\n");
      out.write("\t\t//check to see if in correct format\n");
      out.write("\t\tif(!objRegExp.test(strValue))\n");
      out.write("\t\t    return false; //doesn't match pattern, bad date\n");
      out.write("\t\telse{\n");
      out.write("\t\t\tvar strSeparator = strValue.substring(2,3) //find date separator\n");
      out.write("\t\t    var arrayDate = strValue.split(strSeparator); //split date into month, day, year\n");
      out.write("\t\t    //create a lookup for months not equal to Feb.\n");
      out.write("\t\t    var arrayLookup = { '01' : 31,'03' : 31, '04' : 30,'05' : 31,'06' : 30,'07' : 31,\n");
      out.write("\t\t\t'08' : 31,'09' : 30,'10' : 31,'11' : 30,'12' : 31}\n");
      out.write("\t\t    var intDay = parseInt(arrayDate[0],10);\n");
      out.write("\t\t    //check if month value and day value agree\n");
      out.write("\t\t\tif(arrayLookup[arrayDate[1]] != null) {\n");
      out.write("\t\t      \tif(intDay <= arrayLookup[arrayDate[1]] && intDay != 0)\n");
      out.write("\t\t\t\t\treturn true; //found in lookup table, good date\n");
      out.write("\t\t    \t}\n");
      out.write("\t\t  //check for February\n");
      out.write("\t\t  var intYear = parseInt(arrayDate[2],10);\n");
      out.write("\t\t  var intMonth = parseInt(arrayDate[1],10);\n");
      out.write("\t\t  if( ((intYear % 4 == 0 && intDay <= 29) || (intYear % 4 != 0 && intDay <=28)) && intDay !=0)\n");
      out.write("\t\t  \treturn true; //Feb. had valid number of days\n");
      out.write("\t\t  }\n");
      out.write("\t\t  return false; //any other values, bad date\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("function checkField(){\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\tvar phoneNo=document.myform.phone.value;\n");
      out.write("\t\tvar custName=document.myform.custName.value;\n");
      out.write("\t\tif(custName==\"\") {\n");
      out.write("\t\t\t\talert(\"Please Enter Customer Name\");\n");
      out.write("\t\t\t\treturn false;\n");
      out.write("\t\t}\n");
      out.write("\t\telse if(isNaN(phoneNo)) {\n");
      out.write("\t\t\t\talert(\"Please Enter a number in PhoneNumber field\");\n");
      out.write("\t\t\t\treturn false;\n");
      out.write("\t\t}\n");
      out.write("\t\telse if(phoneNo==\"\") {\n");
      out.write("\t\t\t\talert(\"Please Enter your Phone Number\");\n");
      out.write("\t\t\t\treturn false;\n");
      out.write("\t\t}\n");
      out.write("\t\t\tvar hchck = document.myform.hchckall.value ;\n");
      out.write("\t\t if(hchck != \"0\"){\n");
      out.write("\t\t\tvar c_date1 = document.myform.c_date1.value ;\n");
      out.write("\t\t\tvar c_date2 = document.myform.c_date2.value ;\n");
      out.write("\t\t\tvar u_date1 = document.myform.u_date1.value ;\t\t\t\n");
      out.write("\t\t   if(c_date1!=\"\" ){\t\t\n");
      out.write("\t\t    \t\tvar str = \"\";\n");
      out.write("\t\t\t\t\tstr = str + document.myform.c_date1.value ;\n");
      out.write("\t\t\t\t\t//str = str + document.myform.frMonth.value;\t\n");
      out.write("\t\t\t\t\tif (validateIndiaDate(str) == false){\n");
      out.write("\t\t\t\t\t\talert(\"Please enter a valid From Date\");\n");
      out.write("\t\t\t\t\t\treturn false;\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\tdocument.myform.c_date1.value = document.myform.c_date1.value.substring(6,10) + \"-\" +\n");
      out.write("\t\t\t\t                                document.myform.c_date1.value.substring(3,5) +\n");
      out.write("\t\t\t\t                                \"-\" + document.myform.c_date1.value.substring(0,2);\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t    }\n");
      out.write("\t\t    if(c_date2!=\"\" ){\n");
      out.write("\t\t    \t\tvar str = \"\";\n");
      out.write("\t\t\t\t\tstr = str + document.myform.c_date2.value ;\n");
      out.write("\t\t\t\t\t//str = str + document.myform.frMonth.value;\t\n");
      out.write("\t\t\t\t\tif (validateIndiaDate(str) == false){\n");
      out.write("\t\t\t\t\t\talert(\"Please enter a valid From Date\");\n");
      out.write("\t\t\t\t\t\treturn false;\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\tdocument.myform.c_date2.value = document.myform.c_date2.value.substring(6,10) + \"-\" +\n");
      out.write("\t\t\t\t                                document.myform.c_date2.value.substring(3,5) +\n");
      out.write("\t\t\t\t                                \"-\" + document.myform.c_date2.value.substring(0,2);\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t    }\n");
      out.write("\t\t    if(u_date1!=\"\"){\n");
      out.write("\t\t    \t\tvar str = \"\";\n");
      out.write("\t\t\t\t\tstr = str + document.myform.u_date1.value ;\n");
      out.write("\t\t\t\t\t//str = str + document.myform.frMonth.value;\t\n");
      out.write("\t\t\t\t\tif (validateIndiaDate(str) == false){\n");
      out.write("\t\t\t\t\t\talert(\"Please enter a valid Upadate_date1 Date\");\n");
      out.write("\t\t\t\t\t\treturn false;\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t   \t\t\t document.myform.u_date1.value = document.myform.u_date1.value.substring(6,10) + \"-\" +\n");
      out.write("\t\t\t\t                                document.myform.u_date1.value.substring(3,5) +\n");
      out.write("\t\t\t\t                                \"-\" + document.myform.u_date1.value.substring(0,2);\n");
      out.write("\t\t\t} \n");
      out.write("\t\t}  \n");
      out.write("\t\t\n");
      out.write("\t\tvar ans=confirm(\"Do you really want to save  the changes?\");\n");
      out.write("\t \tif (ans==true){\n");
      out.write("\t  \t\tdocument.myform.action=\"editCustomer.jsp\";\n");
      out.write("\t\t    document.myform.submit();\n");
      out.write("\t \t}\n");
      out.write("\t \telse {\n");
      out.write("\t  \t\tdocument.myform.action=\"HomeForm.jsp\"; \t    \n");
      out.write("\t \t}\t\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction optionDelete(){\n");
      out.write("\t    var order = document.myform.horder.value;\n");
      out.write("\t    if(order!= \"\") {\n");
      out.write("\t    \talert(\"You  Can't Delete This Customer\");\n");
      out.write("\t    \treturn false;\n");
      out.write("\t    }\n");
      out.write("\t\tvar ans=confirm(\"Do you really want to Delete  this Customer?\");\n");
      out.write("\t \tif (ans==true){\n");
      out.write("\t \t\tdocument.myform.hoption.value=1;\t \t\t\n");
      out.write("\t  \t\tdocument.myform.action=\"editCustomer.jsp\";\n");
      out.write("\t\t    document.myform.submit();\n");
      out.write("\t \t}\n");
      out.write("\t \telse {\n");
      out.write("\t  \t\twindow.refresh;\t    \n");
      out.write("\t \t}\t\n");
      out.write("\t }\n");
      out.write("\tfunction showMsg(){\n");
      out.write("\t\tdocument.myform.action=\"EditTargetReportForm.jsp\";\n");
      out.write("\t \tdocument.myform.submit();\n");
      out.write("\t }\n");
      out.write("\t \n");
      out.write("\tfunction Warn(){\n");
      out.write("\t\talert(\"You  Can't Change The Customer Code\");\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("<h3><center>Edit Customer</h3></center>\n");
      out.write("<form name=\"myform\">\n");
      out.write("\t<table  align=\"center\" style=\"width: 700px;\">\n");
      out.write("\t\t<tr style=\"width: 100%;\">\n");
      out.write("\t\t    <td style=\"width: 15%;\"><b>Customer Code</b></td>\n");
      out.write("\t\t    <td style=\"width: 1%\">:</td>\n");
      out.write("\t\t    <td style=\"width: 30%\"><input style=\"width: 100%;\" type=\"text\"  name=\"custCode\"  align=\"right\"  readonly=\"readonly\" value=\"");
      out.print(custCode);
      out.write("\"  onClick=\"Warn();\"></td>\n");
      out.write("\t\t    \n");
      out.write("\t\t    <td style=\"width: 8%\"></td>\n");
      out.write("\t\t     \n");
      out.write("\t\t    <td style=\"width: 15%;\"><b>Mobile Number</b></td>\n");
      out.write("\t\t    <td style=\"width: 1%\">:</td>\n");
      out.write("\t\t    <td style=\"width: 30%\"><input style=\"width: 100%;\" type=\"text\"  name=\"mobileNum\"  align=\"right\" value=\"");
      out.print(mobile);
      out.write("\"></td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr>    \n");
      out.write("\t\t\t<td><b>Customer Name</b></td>\n");
      out.write("\t\t\t<td style=\"width: 1%\">:</td>\n");
      out.write("\t\t\t<td><input style=\"width: 100%;\" type=\"text\" name=\"custName\"  align=\"right\" value=\"");
      out.print(customerName);
      out.write("\"></td>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<td style=\"width: 8%\"></td>\n");
      out.write("\t\t\t \n");
      out.write("\t\t\t<td><b>Phone Number</b></td>\n");
      out.write("\t\t\t<td style=\"width: 1%\">:</td>\n");
      out.write("\t\t\t<td><input style=\"width: 100%;\" type=\"text\" name=\"phone\" size=\"22\"  align=\"right\" colspan=\"2\" value=\"");
      out.print(telephone);
      out.write("\"></td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td ><b>Building</b></td>\n");
      out.write("\t\t\t<td style=\"width: 1%\">:</td>\n");
      out.write("\t\t\t<td><input style=\"width: 100%;\" type=\"text\" name=\"building\"  align=\"right\" value=\"");
      out.print(building);
      out.write("\"></b></td>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<td style=\"width: 8%\"></td>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<td ><b>Building No.</b></td>\n");
      out.write("\t\t\t<td style=\"width: 1%\">:</td>\n");
      out.write("\t\t\t<td><input style=\"width: 100%;\" type=\"text\" name=\"buildingno\"  align=\"right\" value=\"");
      out.print(building_no);
      out.write("\"></b></td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr>\t\n");
      out.write("\t\t    <td><b>Wing</b></td>\n");
      out.write("\t\t    <td style=\"width: 1%\">:</td>\n");
      out.write("\t\t    <td><input style=\"width: 100%;\" type =\"text\" name=\"wing\"  value=\"");
      out.print(wing);
      out.write("\"></td>\n");
      out.write("\t\t    \n");
      out.write("\t\t    <td style=\"width: 8%\"></td>\n");
      out.write("\t\t    \n");
      out.write("     \t\t<td><b>Flat_no</b></td>\n");
      out.write("     \t\t<td style=\"width: 1%\">:</td>\n");
      out.write("     \t\t<td><input style=\"width: 100%;\" type =\"text\" name=\"block\"  align=\"right\" value=\"");
      out.print(block);
      out.write("\"></td>\n");
      out.write("\t\t\t\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td><b>Address1</b></td>\n");
      out.write("\t\t\t<td style=\"width: 1%\">:</td>\n");
      out.write("\t\t\t<td><input style=\"width: 100%;\" type =\"text\" name=\"add1\" value=\"");
      out.print(add1);
      out.write("\"></td>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<td style=\"width: 8%\"></td>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<td><b>Address2</b></td>\n");
      out.write("\t\t\t<td style=\"width: 1%\">:</td>\n");
      out.write("\t\t\t<td><input style=\"width: 100%;\" type =\"text\" name=\"add2\" size=\"22\" value=\"");
      out.print(add2);
      out.write("\"></td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td><b>Area</b></td>\n");
      out.write("\t\t\t<td style=\"width: 1%\">:</td>\n");
      out.write("\t\t\t<td>\n");
 
                String name="";
                Connection conn=null;
				Statement stmt=null;
				ResultSet rs=null;
				try {
					
					Context initContext = new InitialContext();
					Context envContext  = (Context)initContext.lookup("java:/comp/env");
					DataSource ds = (DataSource)envContext.lookup("jdbc/js");
					conn = ds.getConnection();
					stmt = conn.createStatement();
					
					rs = stmt.executeQuery("select value from code_table where category='AREA' order by value asc");
					

      out.write("\n");
      out.write("\t\t\t\t\t<center>\n");
      out.write("\t\t\t\t\t\t<SELECT name=\"area\" align=\"left\" style=\"width: 100%;\">\n");
      out.write("\t\t\t\t\t\t<OPTION VALUE=\"");
      out.print(area);
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print( area);
      out.write(' ');
      out.write('\n');

                           
					 		while (rs.next()) {
					 			name = rs.getString(1);
					 			

      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<OPTION VALUE=\"");
      out.print(name);
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print( name);
      out.write(' ');
      out.write('\n');

							}
					    	
      out.write("\n");
      out.write("\t\t</select></td>\t\n");
      out.write("\t\t\n");
      out.write("\t\t<td style=\"width: 8%\"></td>\n");
      out.write("\t\t\n");
      out.write("\t\t<td><b>Payment Type</b></td>\n");
      out.write("\t\t<td style=\"width: 1%\">:</td>\n");
      out.write("\t\t<td><SELECT name=\"payment\" align=\"left\" style=\"width: 100%;\">\n");
      out.write("\t\t");
 if(payment.equals("")){
      out.write("\n");
      out.write("\t\t\t<OPTION selected VALUE=\"\">Select Type\n");
      out.write("\t\t");
}else{
      out.write('\n');
   
		String q ="SELECT payment_type_desc FROM payment_type where payment_type_code = '"+payment+"'";
		ResultSet rs3 = stmt.executeQuery(q);
    	while (rs3.next()){	

      out.write("\n");
      out.write("\t\t\t<OPTION selected VALUE=\"");
      out.print(payment);
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print(rs3.getString(1));
      out.write("\n");
      out.write("\t\t\t");
 }rs3.close();} 
      out.write('\n');

        ResultSet rs2 = stmt.executeQuery("SELECT payment_type_code, payment_type_desc FROM payment_type");
    	while (rs2.next()){	

      out.write("\n");
      out.write("\n");
      out.write("\t\t<OPTION VALUE=\"");
      out.print(rs2.getString(1));
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print( rs2.getString(2));
      out.write(" </option>\n");
      out.write("\n");
	
        }
        rs2.close();
					    	stmt.close();
					    	conn.close();
					}
					catch (Exception e) {
				       	e.getMessage();
				        e.printStackTrace();  
				        rs.close();
					    stmt.close();
					    conn.close();
				    }      

      out.write("\t\t\t\n");
      out.write("\t\t</select></td>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td><b>Station</b></td>\n");
      out.write("\t\t\t<td style=\"width: 1%\">:</td>\n");
      out.write("\t\t\t<td><input style=\"width: 100%;\" type=\"text\" name=\"station\"  align=\"right\" value=\"");
      out.print(station);
      out.write("\"></td>\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<td style=\"width: 8%\"></td>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t<td><b>Pincode</b></td>\n");
      out.write("\t\t\t<td style=\"width: 1%\">:</td>\n");
      out.write("\t\t\t<td><input style=\"width: 100%;\" type=\"text\" name=\"pincode\" size=\"22\"  align=\"right\" colspan=\"2\" value=\"");
      out.print(pincode);
      out.write("\"></td>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td><b>City</b></td>\n");
      out.write("\t\t\t<td style=\"width: 1%\">:</td>\n");
      out.write("\t\t\t<td><input style=\"width: 100%;\" type=\"text\" name=\"city\"  align=\"right\" value=\"");
      out.print(city);
      out.write("\"></td>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<td style=\"width: 8%\"></td>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<td><b>State</b></td>\n");
      out.write("\t\t\t<td style=\"width: 1%\">:</td>\n");
      out.write("\t\t\t<td><input style=\"width: 100%;\" type=\"text\" name=\"state\"  size=\"22\"  align=\"right\" colspan=\"2\" value=\"");
      out.print(state);
      out.write("\"></td>\n");
      out.write("\t\t</TR>\n");
      out.write("\t\t<TR>\n");
      out.write("\t\t\n");
      out.write("\t\t\t<td align=\"left\" colspan=\"4\"><input type=\"checkbox\" name=\"chckall\" onclick=\"showCustAtt();\">\n");
      out.write("\t\t\t<font color=\"blue\"><b>Additional Information</b></td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t\n");
      out.write("\t\t<tr></tr>\n");
      out.write("\t</table> <br>\t\n");
      out.write("\t<table align=\"center\"><tr><td><div id=\"divcustatt\"> </div></td></tr></table>\n");
      out.write("\t<br>\n");
      out.write("\t<center><input type=\"hidden\" name=\"hcustCode\" value=\"");
      out.print(custCode);
      out.write("\">\n");
      out.write("\t<input type=\"hidden\" name=\"hoption\" value=\"0\">\n");
      out.write("\t<input type=\"submit\" name=\"Submit\" value=\"Submit <Alt+s>\" accesskey=\"s\"  disabled  onClick=\"checkField();return false;\">\n");
      out.write("\t<input type=\"reset\" name=\"clear\" accesskey=\"r\" value=\"Clear <Alt+r>\">\n");
      out.write("\t\t<INPUT type=\"button\" value=\"Delete <Alt+d>\" accesskey=\"d\" onClick=\"optionDelete();\">\n");
      out.write("\t<INPUT type=\"button\" value=\"Cancel <Alt+c>\" accesskey=\"c\" onClick=\"showMsg();\">\n");
      out.write("\t<input  type=\"hidden\" name=\"hchckall\" value=\"0\">\n");
      out.write("\t</center>\n");
      out.write("<hr><br><br> \n");
      out.write("<center><div id=\"txtHint\" class=\"ddm1\" style=\"width: 70%\"></div></center>\n");
      out.write("<p><h1><center><div id=\"waitMessage\"  style=\"cursor: sw-resize\"></center></div></h1></p>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tdocument.myform.custName.focus();\n");
      out.write("\tfunction check(){\n");
      out.write("    \tdocument.myform.Submit.disabled=false;\n");
      out.write("\t}\n");
      out.write("\tdocument.onkeyup = check;\n");
      out.write("\tdocument.onclick = check;\n");
      out.write("\twindow.onload=showHint;\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("</script>\n");
      out.write("</form>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
