/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-02-12 05:45:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import beans.ItemStockOutputBean;
import java.sql.ResultSet;
import beans.jqxgridFormat;
import com.google.gson.Gson;
import beans.JsonOutputBean;
import beans.StockIOutputBean;
import java.util.ArrayList;
import item.ManageItem;

public final class ItemList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String call_option = request.getParameter("call_option");
		if(call_option.equals("item_list")){
			
			String item_name = request.getParameter("item_name");
			String item_code = request.getParameter("item_code");
			String item_group = request.getParameter("item_group");
			String item_barcode = request.getParameter("item_barcode");
			//ManageItem mi = new ManageItem("jdbc/js");
			ManageItem mi = new ManageItem("jdbc/re");
			mi.getItemList(item_name,item_code,item_group,item_barcode);
			ArrayList<StockIOutputBean> listOutputBean = new ArrayList();
			JsonOutputBean jsonOutputBean = new JsonOutputBean();
		
			while(mi.rs.next()){
				
				StockIOutputBean outputBean = new StockIOutputBean();
				outputBean.setItemName(mi.rs.getString(1));
				outputBean.setWeight(mi.rs.getString(2));
				outputBean.setRate(mi.rs.getString(3));
				outputBean.setMrp(mi.rs.getString(4));
				outputBean.setQuntity(mi.rs.getString(5));
				outputBean.setItemCode(mi.rs.getString(6));
				listOutputBean.add(outputBean);
				}
			 
			mi.closeAll();
			jsonOutputBean.setOutputData(listOutputBean);
			jsonOutputBean.getFormat().add(new jqxgridFormat("Item Name","itemName"));
			jsonOutputBean.getFormat().add(new jqxgridFormat("Weight","weight"));
			jsonOutputBean.getFormat().add(new jqxgridFormat("Rate","rate"));
			jsonOutputBean.getFormat().add(new jqxgridFormat("Mrp","mrp"));
			jsonOutputBean.getFormat().add(new jqxgridFormat("Quantity","quntity"));
					
			System.out.println(new Gson().toJson(jsonOutputBean));
			out.println(new Gson().toJson(jsonOutputBean));
		
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t");

		}else if(call_option.equals("item_stock")){
			ManageItem mi = new ManageItem("jdbc/re");
			JsonOutputBean jsonOutputBean = mi.getCurrentStock(request.getParameter("item_code"));
			
			ResultSet resultSet = mi.getSiteNameList();
			
			jsonOutputBean.getFormat().add(new jqxgridFormat("PV   ","itemPV"));
			jsonOutputBean.getFormat().add(new jqxgridFormat("MRP   ","itemMRP"));
			jsonOutputBean.getFormat().add(new jqxgridFormat("Rate   ","itemRate"));
				while(resultSet.next()){
					System.out.println("#"+resultSet.getString("site_name")+"# site"+resultSet.getInt("site_id"));
					jsonOutputBean.getFormat().add(new jqxgridFormat(resultSet.getString("site_name"),"site"+resultSet.getInt("site_id")));
				}	
				
				mi.closeAll();
				System.out.println(new Gson().toJson(jsonOutputBean));
				out.println(new Gson().toJson(jsonOutputBean));
			
			}
		
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
