/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-03-18 09:28:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.naming.*;
import javax.sql.*;

public final class LoginForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    java.lang.Throwable exception = org.apache.jasper.runtime.JspRuntimeLibrary.getThrowable(request);
    if (exception != null) {
      response.setStatus(javax.servlet.http.HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
    }
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("   \n");
      out.write("   \n");
      out.write("   \n");
      out.write("\t\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\n");
      out.write("<style>\n");
      out.write("\n");
      out.write("\tdiv#image{\n");
      out.write("\tbackground-image:url(images/retail4.jpg);\n");
      out.write("\theight:137px;\n");
      out.write("\twidth:100%;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("<!--\n");

	String errMsg="";
	errMsg=request.getParameter("Exp");

      out.write("\n");
      out.write("     \n");
      out.write("\tvar jExp=");
      out.print(errMsg);
      out.write("\n");
      out.write("       \n");
      out.write("\tfunction trimString(str){\n");
      out.write("\t\n");
      out.write("    \treturn str.replace(/^\\s+|\\s+$/g, '');\n");
      out.write("    \t\n");
      out.write("  \t}\n");
      out.write("\n");
      out.write("\tfunction validateString(field, errmsg, lenmsg, min, max, required) { \n");
      out.write("\t\n");
      out.write("\t\tif (!field.value && !required){\n");
      out.write("\t\t\treturn true;\n");
      out.write("\t\t}\n");
      out.write("\t\tif (!field.value){\n");
      out.write("\t   \t\talert(errmsg);\n");
      out.write("\t   \t\tfield.focus(); \n");
      out.write("\t   \t\tfield.select(); \t\t\t  \n");
      out.write("\t   \t\treturn false;\n");
      out.write("\t\t }\n");
      out.write("\t\n");
      out.write("\t\tif (trimString(field.value).length < min || field.value.length > max){\n");
      out.write("\t   \t\talert(lenmsg);\n");
      out.write("\t   \t\tfield.focus(); \n");
      out.write("\t   \t\tfield.select(); \n");
      out.write("\t   \t\treturn false;\n");
      out.write("\t   \t}\n");
      out.write("\t\treturn true; \n");
      out.write("     \n");
      out.write("\t}\n");
      out.write("\tfunction validateOnload(){\n");
      out.write("\tvar jExp=");
      out.print(errMsg);
      out.write("\n");
      out.write("\n");
      out.write(" \t\tif(jExp==1){\n");
      out.write("   \t\t\talert(\"Enter correct name and password\")\n");
      out.write("  \t\t}\n");
      out.write("   \t\telse if(jExp==2){\n");
      out.write("  \t\t\talert(\"You are not activated yet\")\n");
      out.write("  \t\t}\n");
      out.write(" \t \telse if(jExp==3){\n");
      out.write("  \t\t\talert(\"Your Date has been expired\")\n");
      out.write("  \t\t}\n");
      out.write("  \t\telse if(jExp==5){\n");
      out.write("  \t\t\talert(\"Permission Denied!\")\n");
      out.write("  \t\t}\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("//-->\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<center>\n");
      out.write("<form method=\"post\" name=\"LoginForm\" action=\"Login.jsp\"  onSubmit=\"return (validateString(this.username, 'Please enter your name', 'Name must be between 3 and 20 characters', 3, 20, true) && validateString(this.password,'Enter Password','password length should be 6 char or more',6,32,true));\">\n");
      out.write(" <br><br><br><br> \n");
      out.write("\n");
      out.write(" <table>\n");
      out.write("  \t<tr>\n");
      out.write("  \t\t<td align=\"left\">User Name</td>\n");
      out.write("  \t\t<td> : </td>\n");
      out.write("\t\t<td colSpan=2 >\n");
      out.write("\t\t\t<INPUT name=\"username\" accesskey=\"u\" maxlength=\"100\" value=\"\">\n");
      out.write("\t\t</td>\n");
      out.write("\t\t</td>\n");
      out.write("  \t</tr>\n");
      out.write("  \t<tr>\n");
      out.write("\t\t<td align=\"left\"> Password</td>\n");
      out.write("\t\t<td> : </td>\n");
      out.write("\t\t<td colSpan=2 >\n");
      out.write("\t\t\t<INPUT TYPE=password name=\"password\" maxlength=\"32\" accesskey=\"p\" value=\"\"> </td>\n");
      out.write("\t\t</td>\n");
      out.write("  \t</tr>\n");
      out.write("  \t<tr>\n");
      out.write("\t\t<td align=\"left\"> Site Name</td>\n");
      out.write("\t\t<td> : </td>\n");
      out.write("\t\t<td colSpan=2 >\n");
      out.write("\t\t\t<select name=\"siteId\" style=\"width:11em\">\n");
      out.write("\t\t");
	
		 
				try {
					Connection conn=null;
					Statement stmt,stmt1;
					ResultSet rs,rs1;
					Context initContext = new InitialContext();
					Context envContext  = (Context)initContext.lookup("java:/comp/env");
					DataSource ds = (DataSource)envContext.lookup("jdbc/js");
					conn = ds.getConnection();
					stmt = conn.createStatement();
					String selSql = "SELECT site_id, site_name FROM site_master";	
					System.out.print("selSql  "+selSql);
					rs = stmt.executeQuery(selSql);
					String  siteName;
					Integer siteId;
					while(rs.next()){  
						siteId = rs.getInt(1);
						siteName = rs.getString(2);		
						
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(siteId);
      out.write('"');
      out.write('>');
      out.print(siteName);
      out.write("</option>\n");
      out.write("\t\t\t\t\t\t");

						}
					rs.close();	
			        stmt.close();
					conn.close(); 
				}
			catch (Exception e) {
				e.getMessage();
				e.printStackTrace();
				System.out.println(e);
				
			}

      out.write("\n");
      out.write("\t\t\t</select> \n");
      out.write("\t\t</td>\n");
      out.write("  \t</tr>\n");
      out.write("  \t<tr>\n");
      out.write("\t\t<td></td>\n");
      out.write("    \t<td></td>\n");
      out.write("\t\t<td align=\"left\">\n");
      out.write("\t\t\t<INPUT TYPE=image image src=\"images/submit.gif\" name=\"submit\"> </td>\n");
      out.write("\t\t</td>\n");
      out.write("  \t</tr>\n");
      out.write(" </table>\n");
      out.write("</center>\n");
      out.write("</form>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("<!--\n");
      out.write("validateOnload();\n");
      out.write("document.LoginForm.username.focus();\n");
      out.write("//-->\t\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
