/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-02-20 07:58:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.naming.*;
import javax.sql.*;

public final class NewItemGroupForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"ErrorPage.jsp?page=NewItemGroupForm.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write('\n');
      out.write("\n");
      out.write(" \n");
      out.write("\t\n");
      out.write("\t");

	session.getAttribute("UserName").toString();
	//System.out.println("session bachka maapping : "+session +" \n user "+session.getAttribute("UserName").toString());
	
      out.write("\n");
      out.write(" \n");
      out.write("<script>\n");
      out.write("\t");

			String str1="";
		    str1=request.getParameter("Exp");
	
      out.write("\n");
      out.write("\tvar jExp=");
      out.print(str1);
      out.write("\n");
      out.write("\tif(jExp==1){\n");
      out.write("\t\talert(\"Item Group already exists !!!\");\n");
      out.write("\t}\n");
      out.write("\tfunction CheckField(){\n");
      out.write("\t\tvar ig_desc =document.myform.ig_desc.value;\n");
      out.write("\t\tif(ig_desc==\"\") {\n");
      out.write("\t\t\t\talert(\"Please Enter the Item Group\");\n");
      out.write("\t\t\t\tdocument.myform.ig_desc.focus();\n");
      out.write("\t\t\t\treturn false;\n");
      out.write("\t\t}\n");
      out.write("\t\tvar ig_number =document.myform.ig_number.value;\n");
      out.write("\t\tif(isNaN(ig_number)) {\n");
      out.write("\t\t\t\talert(\"Please Enter a number in  Item Group Number field.\");\n");
      out.write("\t\t\t\tdocument.myform.ig_number.focus();\n");
      out.write("\t\t\t\treturn false;\n");
      out.write("\t\t}\n");
      out.write("\t\tvar ans=confirm(\"Do you want to create this Item Group?\");\n");
      out.write("\t\t\tif (ans==true){\t\t\t    \n");
      out.write("\t\t\t\tdocument.myform.action=\"NewItemGroup.jsp\";\n");
      out.write("\t\t\t\tdocument.myform.submit();\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\telse{\n");
      out.write("\t\t\t  window.refresh; \n");
      out.write("\t\t\t}\t\n");
      out.write("\t}\n");
      out.write("</script> \n");
      out.write("<form method=\"post\" name=\"myform\">\n");
      out.write("\t<h3><center>Create New Item Group </center></h3>\n");
      out.write("<table border=\"0\" align=\"center\">\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td><b>Item Group&nbsp&nbsp&nbsp</b></td><td><input type=\"text\" name=\"ig_desc\"></td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td><b>Item Group Number&nbsp&nbsp&nbsp</b></td><td><input type=\"text\" name=\"ig_number\" value=\"0\"></td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td><b>FMCG&nbsp&nbsp&nbsp</b></td><td><input type=\"checkbox\" name=\"fmcg_flag\" onclick=\"SetFlag();\"></td>\n");
      out.write("\t\t</tr>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("<br>\n");
      out.write("\t<input type=\"hidden\" name=\"hfmcg_flag\" value=\"0\">\n");
      out.write("\t<center><input type=\"submit\" name=\"Submit\" value=\"Save<Alt+s>\" accesskey=\"s\" onclick=\"CheckField();return false;\">\n");
      out.write("\t<input type=\"reset\" name=\"clear\" accesskey=\"r\" value=\"Clear <Alt+r>\">\n");
      out.write("\t<INPUT type=BUTTON value=\"Cancel <Alt+c>\" accesskey=\"c\" onClick=\"showMsg();\">\n");
      out.write("\t\t\n");
      out.write("</form>\n");
      out.write("<script>\n");
      out.write("\tfunction showMsg(){\n");
      out.write("\t\t \t document.myform.action=\"HomeForm.jsp\";\n");
      out.write("\t\t\t document.myform.submit();\n");
      out.write("    }\n");
      out.write("  \tfunction SetFlag(){\n");
      out.write("  \t\tif(document.myform.fmcg_flag.checked==true){\n");
      out.write("  \t\t\tdocument.myform.hfmcg_flag.value=1;  \t\t\n");
      out.write("  \t\t}\n");
      out.write("  \t\telse{\n");
      out.write("  \t\t\tdocument.myform.hfmcg_flag.value=0;\n");
      out.write("  \t\t\talert(document.myform.hfmcg_flag.value);\n");
      out.write("  \t\t}\n");
      out.write("  \t}\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
