/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-02-12 05:45:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.*;
import payment.*;
import java.sql.*;
import javax.naming.*;
import javax.sql.*;

public final class NewPackagingReportForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"ReportErrorPage.jsp?page=NewPackagingReport.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "leftsidemenu.jsp", out, false);
      out.write("\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/singleItemStock.css\" />\n");
      out.write("<!-- files for JqxWidget grid  -->\n");
      out.write("\t <link rel=\"stylesheet\" href=\"js/jqwidgets/styles/jqx.base.css\" type=\"text/css\" />\n");
      out.write("\t <link rel=\"stylesheet\" href=\"js/jqwidgets/styles/jqx.darkblue.css\" type=\"text/css\" />\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery-1.10.2.min.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxcore.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxdata.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxbuttons.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxscrollbar.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxlistbox.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxcalendar.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxdatetimeinput.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.filter.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.selection.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.sort.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.pager.js\"></script>\n");
      out.write("     <script type=\"text/javascript\" src=\"js/jqwidgets/jqxmenu.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxlistbox.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxdropdownlist.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxdata.export.js\"></script> \n");
      out.write("     <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.export.js\"></script> \n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.columnsresize.js\"></script> \n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.grouping.js\"></script>\n");
      out.write("\n");
      out.write("<script src=\"js/singleItemStock.js\" type=\"text/javascript\"></script>\n");
      out.write("<script language=\"javascript\" src=\"js/NewPackagingReportForm.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\n");
      out.write("\t");

	session.getAttribute("UserName").toString();
	//System.out.println("session bachka maapping : "+session +" \n user "+session.getAttribute("UserName").toString());
	
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<td width=\"50%\" valign=\"top\" style=\"font-family: arial;\">\n");
      out.write("\t<h2 style=\"float: left;\">Date Wise Packaging Report</h2>\n");
      out.write("\t<table style=\"width: 100%;\">\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td style=\"width: 25%; border: 1px solid black;\" valign=\"top\" align=\"center\">\n");
      out.write("\t\t\t\t<h4>Breakdown Item</h4>\n");
      out.write("\t\t\t\t<table style=\"width: 100%;\">\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td align=left><b><font color=\"blue\">F</font>rom Date</b></td><td align=left>\n");
      out.write("\t\t\t\t\t\t<div id=\"range1\"></div> <INPUT type=\"hidden\" name=\"frDate\" size=11 id=\"frDate\" readonly=\"readonly\"> \n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td align=left><b><font color=\"blue\">T</font>o Date</b></td><td align=left>\n");
      out.write("\t\t\t\t\t\t<div id=\"range2\"></div>\n");
      out.write("\t\t\t\t\t\t<INPUT type=\"hidden\" name=\"toDate\" size=11 id=\"toDate\" readonly=\"readonly\" > \n");
      out.write("\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td colspan=\"3\" style=\"padding-top: 10px;\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" accesskey=\"r\" onclick=\"window.location.reload();\" value=\"Refresh<Alt+r>\"/>\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" accesskey=\"s\" onclick=\"getBreakDownList();\" value=\"Search<Alt+s>\"/>\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t</table>\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t\t<td  valign=\"top\" style=\" width: 70%;\" align=\"center\">\n");
      out.write("\t\t\t\t<div style=\"width: 100%;height: 10%;\" id=\"firstDIV\"></div>\n");
      out.write("\t\t\t\t<div id = \"item_list_td\" style=\"width: 100%;height:95%;\"></div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t</table>  \n");
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("</table>\t\t\n");
      out.write("<div id=\"popupContact\">\n");
      out.write("\t<b style=\"font-size: 16px;\">Breakdown Details </b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a id=\"popupContactClose\">x</a>\n");
      out.write("\t<span id='rowDetails' style=\"text-align: left;\"></span>\n");
      out.write("\t<div id = \"breakdown_info\">\n");
      out.write("\t</div>\t\n");
      out.write("</div>\n");
      out.write("<div id=\"backgroundPopup\"></div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\twindow.onload =function Clear(){\n");
      out.write("\t var flag=true;\n");
      out.write("\t \t\n");
      out.write("\t\t$(\"#range1\").jqxDateTimeInput({theme:'ui-redmond',width: '250px', height: '25px',max:new Date(),formatString: \"yyyy-MM-dd\"});\n");
      out.write("\t\t$(\"#range2\").jqxDateTimeInput({theme:'ui-redmond',width: '250px', height: '25px',min:new Date(),max:new Date(),formatString: \"yyyy-MM-dd\",value:new Date()});\n");
      out.write("\t\t//$(\"#range1\").jqxDateTimeInput({readonly:true});\n");
      out.write("\t\t\n");
      out.write("\t\t$('#range1').on('close', function (event) {\n");
      out.write("\t\t // Some code here. \n");
      out.write("\t\t \t$(\"#range2\").jqxDateTimeInput({disabled: false});\n");
      out.write("\t\t \t$(\"#range2\").jqxDateTimeInput({min: $('#range1').jqxDateTimeInput('getDate')});\n");
      out.write(" \t\t}); \t\n");
      out.write("\t\t\n");
      out.write("\t\tdocument.getElementById(\"frDate\").value =  $('#range1').jqxDateTimeInput('getText');\n");
      out.write("\t\tdocument.getElementById(\"toDate\").value = $('#range2').jqxDateTimeInput('getText');\n");
      out.write("\t\t\n");
      out.write("\t\t$(\"#popupContactClose\").click(function() {\n");
      out.write("\t\t\tdisablePopup();\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t$(\"#backgroundPopup\").click(function() {\n");
      out.write("\t\t\tdisablePopup();\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t$(document).keypress(function(e) {\n");
      out.write("\t\t\tif (e.keyCode == 27 && popupStatus == 1) {\n");
      out.write("\t\t\t\tdisablePopup();\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\treturn false;\n");
      out.write("\t    \n");
      out.write("\t  \t};\n");
      out.write("\t\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
