/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-01-31 07:25:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.naming.*;
import javax.sql.*;

public final class NewUserForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"ErrorPage.jsp?page=NewUserForm.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("     \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\n");
      out.write("\t");

	session.getAttribute("UserName").toString();
	//System.out.println("session bachka maapping : "+session +" \n user "+session.getAttribute("UserName").toString());
	
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");

		String str1="";
	    str1=request.getParameter("Exp");

      out.write("\n");
      out.write("\tvar jExp=");
      out.print(str1);
      out.write("\n");
      out.write("\t\n");
      out.write("\tfunction trimString(str){\n");
      out.write("\t  \treturn str.replace(/^\\s+|\\s+$/g, '');\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction validateString(field, errmsg, lenmsg, min, max, required){\n");
      out.write("\t\tif (!field.value && !required){\n");
      out.write("\t\t    return true;\n");
      out.write("\t\t  }\n");
      out.write("\t\tif (!field.value){\n");
      out.write("\t\t   \talert(errmsg);\n");
      out.write("\t\t  \tfield.focus(); \n");
      out.write("\t\t  \tfield.select(); \t\t\t  \n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t }\n");
      out.write("\t\tif (trimString(field.value).length < min || field.value.length > max){\n");
      out.write("\t\t  \talert(lenmsg);\n");
      out.write("\t\t  \tfield.focus(); \n");
      out.write("\t\t  \tfield.select(); \n");
      out.write("\t\t  \treturn false;\n");
      out.write("\t\t }\n");
      out.write("\t\treturn true; \n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction validateEmail(email, msg, required){ \n");
      out.write("\t\tif (!email.value && !required){ \n");
      out.write("\t\t\treturn true; \n");
      out.write("\t  \t } \n");
      out.write("\t\tvar regEx = /^[\\w-\\.\\+]{1,}\\@([\\da-zA-Z-]{1,}\\.){1,}[\\da-zA-Z-]{2,6}$/; \n");
      out.write("\t\tif (!regEx .test(email.value)){ \n");
      out.write("\t\t\talert(msg); \n");
      out.write("\t\t\temail.focus(); \n");
      out.write("\t\t\temail.select(); \t\n");
      out.write("\t\t\treturn false; \n");
      out.write("\t\t} \n");
      out.write("\t\treturn true; \n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction showMsg(){\n");
      out.write("\t\t \t document.NewUserForm.action=\"HomeForm.jsp\";\n");
      out.write("\t\t\t document.NewUserForm.submit();\n");
      out.write("    }\n");
      out.write("\t\n");
      out.write("\tfunction ClearAll(){\n");
      out.write("\t\tdocument.NewUserForm.userName.value=\"\";\n");
      out.write("\t\tdocument.NewUserForm.userPasswd.value=\"\";\n");
      out.write("\t\tdocument.NewUserForm.eEmail.value = \"\";\n");
      out.write("\t\tdocument.NewUserForm.contactNo.value = \"\";\n");
      out.write("\t\treturn false;\n");
      out.write("\t }\n");
      out.write("\t\n");
      out.write("\tif(jExp==1){\n");
      out.write("\t\talert(\"User Name already exists !!!\");\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("<style>\n");
      out.write("form fieldset {\n");
      out.write("\tborder: 1px solid #21221A;\n");
      out.write("\twidth: 400px; \n");
      out.write("\theight:auto;\n");
      out.write("\tbackground-color:white;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<p>\n");
      out.write(" <br><br>\n");
      out.write("\t\t<center>\n");
      out.write("\t \t<br>\n");
      out.write("<form method=\"post\" name=\"NewUserForm\" action=\"NewUser.jsp\"  onSubmit=\"return(validateString(this.userName, 'Please enter your name', 'Name must be between 3 and 20 characters', 3, 20, true)&& validateString(this.userPasswd, 'Please enter Password', 'Passwd Length should Be Six Chars Or More', 6, 20, true) && validateEmail(this.eEmail, 'Please enter a valid email address', true) ) ;\">\n");
      out.write("\t \t<fieldset><legend><font size=\"4\"><b> New user creation </b></font></legend>\n");
      out.write("\t \t<br/>\n");
      out.write("\t \t<table align=\"center\">\n");
      out.write("\t \t    <tr>\n");
      out.write("\t\t\t     <td align=\"left\"><b><font color=\"blue\">U</font>ser Name </td><td> : </td>\n");
      out.write("\t\t\t     <td><input name=\"userName\" id=\"userName\"  type=\"text\" maxlength=\"20\" value=\"\" accesskey=\"u\"><br></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr></tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t      <td align=\"left\"><b><font color=\"blue\">P</font>assword</td><td> : </td>\n");
      out.write("\t\t\t      <td><input name=\"userPasswd\" id=\"userPasswd\"  type=\"password\"  maxlength=\"20\" value=\"\"  accesskey=\"p\"></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr></tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t      <td align=\"left\"><b><font color=\"blue\">T</font>ype Of User</td><td> : </td>\n");

	Connection conn=null;
	Statement stmt=null;
	ResultSet rs=null;
	try {
		String name,desc;
		int rowcount;
		Context initContext = new InitialContext();
		Context envContext  = (Context)initContext.lookup("java:/comp/env");
		DataSource ds = (DataSource)envContext.lookup("jdbc/js");
		conn = ds.getConnection();
		stmt = conn.createStatement();
		rs = stmt.executeQuery("select user_type_code, user_type_desc from user_type");

      out.write("\n");
      out.write("\t\t\t      \t<td>\n");
      out.write("\t\t\t\t\t\t<SELECT name=\"userType\"  maxlength=\"20\" accesskey=\"t\" style=\"width:11em\">\n");
 
		rowcount = 0;
	 	while (rs.next()) {
	 		name = rs.getString(1);
	 		desc = rs.getString(2);
	 		if (rowcount==0) { 
 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<OPTION VALUE=\"");
      out.print( name);
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print( desc);
      out.write("</OPTION>\n");

  			}
   			else {

      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<OPTION VALUE=\"");
      out.print( name);
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print( desc);
      out.write("</OPTION>\n");

			} 
			rowcount++;
		}
		rowcount=0;
	    rs.close();
	    stmt.close();
	    conn.close();
    }
	catch (Exception e) {
        e.getMessage();
        e.printStackTrace();
        rs.close();
    	stmt.close();
    	conn.close();
   }

      out.write("\n");
      out.write("\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t</SELECT>\n");
      out.write("\t\t\t\t</TR>\n");
      out.write("\t\t\t\t<tr></tr>\n");
      out.write("\t\t\t    <tr>\n");
      out.write("\t\t\t\t\t<td align=\"left\"><b><font color=\"blue\">E</font>mail Id</td><td> : </td>\n");
      out.write("\t\t\t\t   \t<td><input name=\"eEmail\" id=\"eEmail\" type=\"text\" maxlength=40 value=\"\" accesskey=\"e\"></td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr></tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td align=\"left\"><b><font color=\"blue\">C</font>ontact No</td><td> : </td>\n");
      out.write("\t\t\t\t    <td><input name=\"contactNo\" id='contactNo' type=\"text\" size=20 maxlength=20 accesskey=\"c\"></td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t</table><br><br>\n");
      out.write("\t\t\t<center><input name=\"Operation\" type=\"hidden\" value=\"\" ></center>\n");
      out.write("\t\t\t<center><INPUT type=\"submit\" value=\"Submit\" name=\"Submit\" disabled accesskey=\"s\">&nbsp; <INPUT type=\"reset\" value=\"Clear\" accesskey=\"r\" onClick=\"ClearAll();return false;\">&nbsp&nbsp<INPUT type=BUTTON value=\"Cancel\" accesskey=\"s\" onClick=\"showMsg();\"></center>\n");
      out.write("   \n");
      out.write("</fieldset></form></center>\n");
      out.write("<script>\n");
      out.write("\tdocument.NewUserForm.userName.focus();\n");
      out.write("\tfunction check(){\n");
      out.write("    \tdocument.NewUserForm.Submit.disabled=false;\n");
      out.write("\t}\n");
      out.write("\tdocument.onkeyup = check;\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
