/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-02-22 11:27:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import customer.ManageCustomer;

public final class PrintSelectedCustPayment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write(" \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function printRecept(){\r\n");
      out.write("   var html=\"<html>\";\r\n");
      out.write("   html+= document.getElementById(\"pay_recept\").innerHTML;\r\n");
      out.write("   html+=\"</html>\";\r\n");
      out.write("\r\n");
      out.write("   var printWin = window.open('','','left=350,top=100,height=400,toolbar=0,scrollbars=2,status=0,font-family=consolas');\r\n");
      out.write("   printWin.document.write(html);\r\n");
      out.write("   printWin.document.close();\r\n");
      out.write("   printWin.focus();\r\n");
      out.write("   printWin.print();\r\n");
      out.write("   printWin.close();\r\n");
      out.write("   window.location=\"EditTargetReportForm.jsp?call_type=search_payment\";\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");

String orders[] = request.getParameterValues("orders");
String orders_count = request.getParameter("order_count");
ManageCustomer manage= new ManageCustomer("jdbc/js");
manage.getPaymentList(orders);

      out.write("\r\n");
      out.write("<br/><br/>\r\n");
      out.write("<div id = \"pay_recept\" style=\"border:1px Solid Black;font-family: consolas;\" align=\"center\">\r\n");
      out.write("Customer Detail for pending collection(");
      out.print(orders_count );
      out.write(" orders)\r\n");
      out.write("<table border=\"1\" style=\"border-collapse: collapse;\">\r\n");
      out.write("<tr>\r\n");
      out.write("\t<th style=\"width: 6%;\">Code</th>\r\n");
      out.write("\t<th style=\"width: 20%;\">Name</th>\r\n");
      out.write("\t<th style=\"width: 5%;\">Balance</th>\r\n");
      out.write("\t<th style=\"width: 5%;\">Order</th>\r\n");
      out.write("\t<th style=\"width: 10%;\"> Ord Date</th>\r\n");
      out.write("\t<th style=\"width: 10%;\"> Del Date</th>\r\n");
      out.write("\t<th style=\"width: 7%;\">Phone</th>\r\n");
      out.write("\t<th style=\"width: 7%;\">Mobile</th>\r\n");
      out.write("\t<th style=\"width: 30%;\">Address</th>\r\n");
      out.write("</tr>\r\n");

while(manage.rs.next()){
	String addr = manage.rs.getString(8)+", "+manage.rs.getString(9)+", "+manage.rs.getString(10)+", "+manage.rs.getString(11)+", "
			+manage.rs.getString(12)+", "+manage.rs.getString(13)+", "+manage.rs.getString(14)+", "+manage.rs.getString(17);
	
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td valign=\"top\">");
      out.print(manage.rs.getString(1) );
      out.write("</td>\r\n");
      out.write("\t\t<td valign=\"top\">");
      out.print(manage.rs.getString(2) );
      out.write("</td>\r\n");
      out.write("\t\t<td valign=\"top\">");
      out.print(manage.rs.getString(3) );
      out.write("</td>\r\n");
      out.write("\t\t<td valign=\"top\">");
      out.print(manage.rs.getString(4) );
      out.write("</td>\r\n");
      out.write("\t\t<td valign=\"top\">");
      out.print(manage.rs.getString(5) );
      out.write("</td>\r\n");
      out.write("\t\t<td valign=\"top\">");
      out.print(manage.rs.getString(18) );
      out.write("</td>\r\n");
      out.write("\t\t<td valign=\"top\">");
      out.print(manage.rs.getString(6) );
      out.write("</td>\r\n");
      out.write("\t\t<td valign=\"top\">");
      out.print(manage.rs.getString(7) );
      out.write("</td>\r\n");
      out.write("\t\t<td valign=\"top\">");
      out.print(addr );
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t");

}

      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("<div >\r\n");
      out.write("\t<input type=\"button\" accesskey=\"p\" onclick=\"printRecept()\" value=\"Print <Alt+p>\"/>\r\n");
      out.write("</div>\r\n");

manage.closeAll();

      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
