/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-02-05 07:50:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.naming.*;
import javax.sql.*;

public final class RDeliveryMonthlyReportForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"ReportErrorPage.jsp?page=RDeliveryMonthlyReportForm.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write('\n');
      out.write("\n");
      out.write(" \n");
      out.write("\n");
      out.write("\t\n");
      out.write("\t");

	session.getAttribute("UserName").toString();
	//System.out.println("session bachka maapping : "+session +" \n user "+session.getAttribute("UserName").toString());
	
      out.write('\n');
      out.write(' ');
      out.write('\n');

if(session.getAttribute("user_type_code") != null){
String userTypeCode=session.getAttribute("user_type_code").toString();

      out.write("\t\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
	
	if(!userTypeCode.equals("3")){

      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "leftsidemenu.jsp", out, false);
      out.write('\n');
}
      out.write("\n");
      out.write(" \n");
      out.write("\n");
      out.write("  \n");
      out.write("<style>\n");
      out.write("hr {\n");
      out.write("color: #f00;\n");
      out.write("background-color: #f00;\n");
      out.write("height: 3px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<script>\n");
      out.write("\tfunction checkField(){\n");
      out.write("\t\t\n");
      out.write("\t\tvar selMonth= document.myform.selMonth.value;\n");
      out.write("\t\tvar check1=document.myform.hchckall.value;\n");
      out.write("\t\tif(document.myform.chckall.checked==false && selMonth == \"\"){\n");
      out.write("\t\t\talert(\"Select the month\");\n");
      out.write("\t\t\tdocument.myform.selMonth.focus();\n");
      out.write("\t\t\t\n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t}\n");
      out.write("\t\tdocument.myform.action=\"RDeliveryMonthlyReport.jsp?Exp=0\";\n");
      out.write("\t\tdocument.myform.submit();\n");
      out.write("\t    \n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("<form method=\"post\" name=\"myform\" >\n");
      out.write("<td width=\"50%\">\n");
      out.write("\t<h3><center>Monthly Reports </center></h3>\n");
      out.write("\t\n");
      out.write("\t<center><b><font color=\"blue\">&nbspA</font>ll &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<input type=\"CheckBox\" name=\"chckall\" checked onClick=\"funEnabled();\"></center>\n");
      out.write("\t<br><br>\n");
      out.write("\t<div id=\"div4\" style=\"VISIBILITY:hidden\" align=\"center\">\t\t\n");
      out.write("\t\t<table border=\"0\" align=\"center\">\t\t\n");
      out.write("\t\t\t\t<tr></tr>\n");
      out.write("\t\t\t\t<tr></tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td colspan=4><fieldset><legend>Range</legend><table align=\"center\">\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<tr></tr>\n");
      out.write("\t\t\t\t\t<tr></tr>\n");
      out.write("\t\t\t\t\t<tr></tr>\n");
      out.write("\t\t\t\t\t<tr></tr>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<td><b>Select <font color=\"blue\">M</font>onth</b></td>\n");
      out.write("\t\t\t\t\t\t\t<td> <SELECT name=\"selMonth\">\n");
      out.write("\t\t\t\t\t\t\t<OPTION VALUE=\"\"> Select\n");
					
					String months[] = {"January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"};
       /*{"Jan", "Feb", "Mar", "Apr", "May", "Jun", 
        "July", "Aug", "Sep", "Oct", "Nov", "Dec"};*/
        

   //use the length attribute to get the number
   //of elements in an array
   for(int i = 0; i < months.length; i++ ) {
      
 


      out.write("\n");
      out.write("\t\t\t\t\t<OPTION VALUE=\"");
      out.print(months[i]);
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print(months[i]);
      out.write('\n');
}
      out.write("\n");
      out.write("\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t<tr></tr>\n");
      out.write("\t\t\t\t\t<tr></tr>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</table></fieldset></td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t</table></div>\n");
      out.write("\n");
      out.write("<br>\n");
      out.write("\t<input  type=\"hidden\" name=\"hchckall\" value=\"1\">\n");
      out.write("\t<center><input type=\"submit\" name=\"Submit\" value=\"Search <Alt+s>\" accesskey=\"s\" onclick=\"checkField();return false;\">\n");
      out.write("\t<input type=\"reset\" name=\"clear\" accesskey=\"r\" value=\"Clear <Alt+r>\" onclick=\"document.getElementById('txtHint').innerHTML='';\">\n");
      out.write("\t<INPUT type=BUTTON value=\"Cancel <Alt+c>\" accesskey=\"c\" onClick=\"showMsg();\">\n");
      out.write("\t\n");
      out.write("\t</td></tr></table>\t\n");
      out.write("</form>\n");
      out.write("<script>\t\n");
      out.write("\tfunction showMsg(){\n");
      out.write("\t\t \t document.myform.action=\"HomeForm.jsp\";\n");
      out.write("\t\t\t document.myform.submit();\n");
      out.write("    }\n");
      out.write("\tfunction funEnabled(){\n");
      out.write("\t    if (document.myform.chckall.checked==true){\n");
      out.write("\t\t\tdocument.getElementById('div4').style.visibility=\"hidden\";\n");
      out.write("\t\t\tdocument.myform.hchckall.value=1;\t\t\t\t\t\n");
      out.write("\t\t}\n");
      out.write("\t\telse{\n");
      out.write("\t\t\tdocument.getElementById('div4').style.visibility=\"visible\";\n");
      out.write("\t\t\tdocument.myform.hchckall.value=0;\t\t\t\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\twindow.onload=Clear;\n");
      out.write("\t\t\n");
      out.write("\t\tfunction Clear(){\t\t\t\n");
      out.write("\t\t\tdocument.myform.chckall.checked=true;\t\n");
      out.write("\t\t\tdocument.myform.hchckall.value=\"1\";\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t}\n");
      out.write("</script>\n");
} 
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
