/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-02-24 10:20:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Calendar;
import payment.*;

public final class ReceivePaymentAjaxResponse_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

String call_option = request.getParameter("call_option");
if(call_option.equals("cust_info")){
	String cust_code = request.getParameter("cust_code");
	ManagePayment manage = new ManagePayment("jdbc/js");
	manage.getCustInfo(cust_code);
	if(manage.rs.next()){
		
      out.write("\r\n");
      out.write("\t\t\t<h3>&nbsp;Customer Detail :</h3>\r\n");
      out.write("\t\t\t<b>Name : </b> ");
      out.print( manage.rs.getString(1) );
      out.write(" &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>Phone : </b> ");
      out.print( manage.rs.getString(9)+" , "+ manage.rs.getString(10) );
      out.write("<br/>\r\n");
      out.write("\t\t\t<b>Address : </b> ");
      out.print( manage.rs.getString(2)+" Building, "+manage.rs.getString(3)+" Block, "+manage.rs.getString(4)+" Wing, " );
      out.write("\r\n");
      out.write("\t\t\t ");
      out.print( manage.rs.getString(5)+" , "+manage.rs.getString(6)+" , "+manage.rs.getString(8) );
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t <b>Station : </b> ");
      out.print( manage.rs.getString(7) );
      out.write("<br/>\r\n");
      out.write("\t\t\t<input type=\"button\" accesskey=\"s\" value=\"Search Again<Alt+S>\" onclick=\"goBack()\"/>\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"cust_name\" value = \"");
      out.print( manage.rs.getString(1) );
      out.write("\"/>\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"address\" value = \"");
      out.print( manage.rs.getString(2)+" Building, "+manage.rs.getString(3)+" Block, "+manage.rs.getString(4)+" Wing, " );
      out.write("\r\n");
      out.write("\t\t\t ");
      out.print( manage.rs.getString(5)+" , "+manage.rs.getString(6)+" , "+manage.rs.getString(8) );
      out.write("\"/>\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"phone\" value = \"");
      out.print( manage.rs.getString(9)+" , "+ manage.rs.getString(10) );
      out.write("\"/>\r\n");
      out.write("\t\t");

	} else {
		out.print("Error in Fatching data...");
	}
	int last_pay = manage.getLastPayFromTable();
	last_pay++;
	String id = "RP"+last_pay;
	
      out.write("\r\n");
      out.write("\t<input type=\"hidden\" name=\"pay_code\" value = \"");
      out.print(id);
      out.write("\"/>\r\n");
      out.write("\t\r\n");
      out.write("\t");

	manage.closeAll();
} else if(call_option.equals("order_info")){
	String cust_code = request.getParameter("cust_code");
	ManagePayment manage = new ManagePayment("jdbc/js");
	manage.getOrderInfo(cust_code);
	
      out.write("\r\n");
      out.write("\t<div id = \"refresh_button\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input style=\"float: right;margin-top: 5px;\" type=\"button\" onclick=\"distributePayment()\" value=\"Distribute All<Alt+D>\" accesskey=\"d\"/> \r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<img id = \"refresh_button_img\" src=\"images/refresh.png\" onclick=\"loadCustDetails('");
      out.print( cust_code);
      out.write("'),manageAmount()\" title=\"Refresh Order Detail Table\"/>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<center><h4>Order Details</h4></center>\r\n");
      out.write("\t<div style=\"width: 99%;overflow-y:scroll;\">\r\n");
      out.write("\t\t<table border=\"1\" style=\"width: 98%; float: right;background-color: #BEF781;\">\r\n");
      out.write("\t\t\t<tr style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t<th style=\"width: 8%;\">O.No.</th>\r\n");
      out.write("\t\t\t\t<th style=\"width: 9%;\">Date</th>\r\n");
      out.write("\t\t\t\t<th style=\"width: 9%;\">Total</th>\r\n");
      out.write("\t\t\t\t<th style=\"width: 9%;\">Change</th>\r\n");
      out.write("\t\t\t\t<th style=\"width: 9%;\">Paid</th>\r\n");
      out.write("\t\t\t\t<th style=\"width: 9%;\">Advance</th>\r\n");
      out.write("\t\t\t\t<th style=\"width: 9%;\">Discount</th>\r\n");
      out.write("\t\t\t\t<th style=\"width: 9%;\">Other</th>\r\n");
      out.write("\t\t\t\t<th style=\"width: 9%;\">Balance</th>\r\n");
      out.write("\t\t\t\t<th style=\"width: 3%;\">&nbsp;</th>\r\n");
      out.write("\t\t\t\t<th style=\"width: 9%;\">Amount</th>\r\n");
      out.write("\t\t\t\t<th style=\"width: 8%;\">Waived</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"width: 99%;max-height: 120px;overflow-y:scroll;\">\r\n");
      out.write("\t\t<table border=\"1\" style=\"width: 98%;float: right;\">\r\n");
      out.write("\t\t");

		int count = 0;
		float total_balance = 0f;
		if(manage.rs.next()){
		do{
			if(count%2==0){
			
      out.write("\r\n");
      out.write("\t\t\t\t<tr style=\"width: 100%;background-color:#ECFBB9;\">\r\n");
      out.write("\t\t\t");

			}else{
				
      out.write("\r\n");
      out.write("\t\t\t\t<tr style=\"width: 100%;background-color:#ECFB99;\">\r\n");
      out.write("\t\t\t\t");

			}
			
      out.write("\r\n");
      out.write("\t\t\t\t<td style=\"width: 8%; cursor: pointer;\" align=\"left\">\r\n");
      out.write("\t\t\t\t<table><tr><td>\r\n");
      out.write("\t\t\t\t<b><u>\r\n");
      out.write("\t\t\t\t<font color=blue onclick=\"displayOrderDetail('");
      out.print(manage.rs.getString(1));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print( manage.rs.getDate(2) );
      out.write("')\">");
      out.print(manage.rs.getString(1));
      out.write("</font>\r\n");
      out.write("\t\t\t\t</u></b></td><td>\r\n");
      out.write("\t\t\t\t<div id=\"return_arrow\" style=\"width: 18px;height: 18px; float: right;background-image: url(images/return_item.png)\" onclick=\"returnItemPage('");
      out.print(manage.rs.getString(1));
      out.write("')\"></div>\r\n");
      out.write("\t\t\t\t</td></tr></table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td style=\"display:none;\"><input type=\"hidden\" name=\"ord_num\" size=\"7\" id=\"order_num_");
      out.print(count);
      out.write("\" value = \"");
      out.print(manage.rs.getString(1));
      out.write("\"/></td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 9%;\">");
      out.print( manage.rs.getDate(2) );
      out.write("<input type=\"hidden\" name=\"date\" value=\"");
      out.print( manage.rs.getDate(2) );
      out.write("\"/></td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 9%;\">");
      out.print( manage.rs.getFloat(3) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 9%;\">");
      out.print( manage.rs.getFloat(4) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 9%;\">");
      out.print( manage.rs.getFloat(5) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 9%;\">");
      out.print( manage.rs.getFloat(6) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 9%;\">");
      out.print( manage.rs.getFloat(7) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 9%;\">");
      out.print( manage.rs.getFloat(9) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 9%;\" id=\"balance_");
      out.print(count);
      out.write('"');
      out.write('>');
      out.print( manage.rs.getFloat(8) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td style=\"display:none;\"><input type=\"hidden\" name=\"balance\" value=\"");
      out.print( manage.rs.getFloat(8) );
      out.write("\"/></td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 3%;\"><img id=\"arrow_image\" src=\"images/a1.png\" onclick=\"copyAmount('balance_");
      out.print(count);
      out.write("','amount_");
      out.print(count);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(count);
      out.write("')\"></td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 9%;\" align=\"left\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"dist_amt\" size=\"5\" id=\"amount_");
      out.print(count);
      out.write("\" value=\"0\" readonly=\"readonly\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"right_");
      out.print(count);
      out.write("\" class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/right_icon.png\" style=\"width: 26px; height: 26px;margin-top: -7px;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"wrong_");
      out.print(count);
      out.write("\" class=\"wrong\" onclick=\"confirmDiscount('amount_");
      out.print(count);
      out.write("','balance_");
      out.print(count);
      out.write("','waived_");
      out.print(count);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(count);
      out.write("');\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/wrong_icon.png\" style=\"width: 20px; height: 20px;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 8%;\" align=\"left\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" size=\"4\" id=\"waived_");
      out.print(count);
      out.write("\" name=\"waived\" value = \"0\" readonly=\"readonly\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"undo_");
      out.print(count);
      out.write("\" class=\"undo\" onclick=\"undoDiscount('amount_");
      out.print(count);
      out.write("','balance_");
      out.print(count);
      out.write("','waived_");
      out.print(count);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(count);
      out.write("')\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/undo.png\" style=\"width: 24px; height: 24px;margin-top: -7px;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t");

		total_balance = total_balance + manage.rs.getFloat(8);
		count++;
		} while(manage.rs.next());
		}else{
		
      out.write("\r\n");
      out.write("\t\t\t<tr style=\"width: 100%;background-color:#ECFBB9;\"><td colspan=\"12\">No Pending</td><tr>\r\n");
      out.write("\t\t");

		}
		manage.closeAll();
		
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"height: 30px;width: 89%;margin-right: 20px;\" align=\"right\">\r\n");
      out.write("\t<b id=\"grand_total_balance\">");
      out.print( total_balance );
      out.write("</b><b> /-Rs.</b> Total Balance.</div>\r\n");
      out.write("\t<input type=\"hidden\" name=\"row_count\" value=\"");
      out.print( count );
      out.write("\" id=\"row_count\"/>\r\n");
      out.write("\t");

} else if(call_option.equals("recent_payment")){
	String cust_code = request.getParameter("cust_code");
	ManagePayment manage = new ManagePayment("jdbc/js");
	manage.getRecentPaymentDetail(cust_code);
	
      out.write("\r\n");
      out.write("\t<div style=\"width: 99%;overflow-y:scroll;\">\r\n");
      out.write("\t\t<table border=\"1\" style=\"width: 96%;background-color: #BEF781;float: right;\">\r\n");
      out.write("\t\t\t<tr style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t<th style=\"width: 33.33%;\">Date</th>\r\n");
      out.write("\t\t\t\t<th style=\"width: 33.33%;\">Amount</th>\r\n");
      out.write("\t\t\t\t<th style=\"width: 33.33%;\">Receive By</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"width: 99%;max-height :85%;overflow-y:scroll\">\r\n");
      out.write("\t\t<table border=\"1\" style=\"width: 96%;;background-color: #BEF781;float: right;\">\r\n");
      out.write("\t");

	int count = 0;
	if(manage.rs.next()){
	do{
		if(count%2==0){
			
      out.write("\r\n");
      out.write("\t\t\t\t<tr style=\"width: 100%;background-color:#ECFBB9;cursor: pointer;\" \r\n");
      out.write("\t\t\t\tonclick=\"loaadDetailSinglePayment('");
      out.print(manage.rs.getString(2));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print( manage.rs.getString(4) );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print( manage.rs.getString(7) );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print( manage.rs.getDate(6) );
      out.write("')\">\r\n");
      out.write("\t\t\t");

			}else{
			
      out.write("\r\n");
      out.write("\t\t\t\t<tr style=\"width: 100%;background-color:#ECFB99;cursor: pointer;\" \r\n");
      out.write("\t\t\t\tonclick=\"loaadDetailSinglePayment('");
      out.print(manage.rs.getString(2));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print( manage.rs.getString(4) );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print( manage.rs.getString(7) );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print( manage.rs.getDate(6) );
      out.write("')\">\r\n");
      out.write("\t\t\t");

			}
		
      out.write("\r\n");
      out.write("\t\t\t\t<td style=\"width: 33.33%;padding-left: 10px;\" align=\"left\">");
      out.print( manage.rs.getDate(6) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 33.33%;padding-left: 10px;\" align=\"left\">");
      out.print( manage.rs.getString(4) );
      out.write("&nbsp;Rs.</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 33.33%;padding-left: 10px;\" align=\"left\">");
      out.print( manage.rs.getString(7) );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t");

	count++;
	}while(manage.rs.next());
	}else{
	
      out.write("\r\n");
      out.write("\t<tr style=\"width: 100%;background-color:#ECFBB9;\"><td colspan=\"3\">No Previous Payment</td></tr>\r\n");
      out.write("\t");

	}
	
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");

	manage.closeAll();
} else if(call_option.equals("detail_payment") || call_option.equals("detail_payment1")){
	String pay_code = request.getParameter("pay_code");
	ManagePayment manage = new ManagePayment("jdbc/js");
	manage.getPaymentDetail(pay_code);
	
      out.write("\r\n");
      out.write("\t<b>Date : </b>");
      out.print(request.getParameter("date") );
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>Amount : </b>");
      out.print(request.getParameter("amount") );
      out.write("\r\n");
      out.write("\t<br/><br/>\r\n");
      out.write("\t<div style=\"width: 99%;overflow-y:scroll;\">\r\n");
      out.write("\t\t<table border=\"1\" style=\"width: 97%;float: right;background-color: #BEF781;\">\r\n");
      out.write("\t\t\t<tr style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t<th style=\"width: 25%;\">Order No</th>\r\n");
      out.write("\t\t\t\t<th style=\"width: 25%;\">Date</th>\r\n");
      out.write("\t\t\t\t<th style=\"width: 25%;\">Amount</th>\r\n");
      out.write("\t\t\t\t<th style=\"width: 25%;\">Receive By</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"width: 99%;max-height :67%;overflow-y:scroll;max-height: 200px;\">\r\n");
      out.write("\t\t<table border=\"1\" style=\"width: 97%;background-color: #BEF781;float: right;\">\r\n");
      out.write("\t");

	int count = 0;
	while(manage.rs.next()){
		if(count%2==0){
			
      out.write("\r\n");
      out.write("\t\t\t\t<tr style=\"width: 100%;background-color:#ECFBB9;cursor: pointer;\"> \r\n");
      out.write("\t\t\t");

			}else{
			
      out.write("\r\n");
      out.write("\t\t\t\t<tr style=\"width: 100%;background-color:#ECFB99;cursor: pointer;\" >\r\n");
      out.write("\t\t\t");

			}
		if(call_option.equals("detail_payment")){
			
      out.write("\r\n");
      out.write("\t\t\t\t<td style=\"width: 25%;padding-left: 10px;\" align=\"left\"  onclick=\"displayOrderDetail('");
      out.print(manage.rs.getString(2));
      out.write("')\">\r\n");
      out.write("\t\t\t\t<b><u><font color=blue>");
      out.print(manage.rs.getString(2));
      out.write("</font></u></b></td>\r\n");
      out.write("\t\t\t");

		}else{
			
      out.write("\r\n");
      out.write("\t\t\t<td style=\"width: 25%;padding-left: 10px;\" align=\"left\">\r\n");
      out.write("\t\t\t");
      out.print(manage.rs.getString(2));
      out.write("</td>\r\n");
      out.write("\t\t\t");

		}
			
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<td style=\"width: 25%;padding-left: 10px;\" align=\"left\">");
      out.print(request.getParameter("date") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 25%;padding-left: 10px;\" align=\"left\">\r\n");
      out.write("\t\t\t\t");

					out.print(manage.rs.getString(3)+" /-Rs.");
					if(Float.parseFloat(manage.rs.getString(5)) > 0){
						out.print("("+manage.rs.getString(5)+" Rs. Waived)");
					}
				
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 25%;padding-left: 10px;\" align=\"left\">");
      out.print(request.getParameter("receive_by") );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t");

	count++;
	}
	
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");

	manage.closeAll();
}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
