/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-03-17 06:01:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.google.gson.Gson;
import beans.JsonOutputBean;
import java.util.ArrayList;
import beans.SalesOutputBean;
import java.sql.*;
import javax.naming.*;
import javax.sql.*;
import java.io.*;
import java.text.*;

public final class ReportDifferenceListWithAllDate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"ReportErrorPage.jsp?page=ReportDifferenceListWithAllDate.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- files for JqxWidget grid  -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"js/jqwidgets/styles/jqx.base.css\" type=\"text/css\" />\n");
      out.write("    <link rel=\"stylesheet\" href=\"js/jqwidgets/styles/jqx.darkblue.css\" type=\"text/css\" />\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery-1.10.2.min.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxcore.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxdata.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxbuttons.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxscrollbar.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxlistbox.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxcalendar.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxdatetimeinput.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.filter.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.selection.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.sort.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.pager.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxmenu.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxlistbox.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxdropdownlist.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxdata.export.js\"></script> \n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.export.js\"></script> \n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.columnsresize.js\"></script> \n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.aggregates.js\"></script> \n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.grouping.js\"></script>\t\n");
      out.write(" \n");
      out.write("\n");
      out.write("\t\n");
      out.write("\t");

	session.getAttribute("UserName").toString();
	//System.out.println("session bachka maapping : "+session +" \n user "+session.getAttribute("UserName").toString());
	
      out.write('\n');
      out.write(' ');
      out.write('\n');

			String str1="";
		    str1=request.getParameter("Exp");		    
		    if(str1.equals("1")){		    	
		    	response.setContentType("application/vnd.ms-excel");    
		    }else{		 
		    	response.setContentType("text/html");		    
		    }

      out.write("\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<title>Sales... </title>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\n");
      out.write("<style>\n");
      out.write("body{\n");
      out.write("\tfont-family: arial;\n");
      out.write("\t}\n");
      out.write(".boldtable, .boldtable TD, .boldtable TH\n");
      out.write("{\n");
      out.write("\tfont-family:arial;\n");
      out.write("\tfont-size:10pt;\n");
      out.write("}\n");
      out.write("#id{\n");
      out.write("\tborder-collapse: collapse;\n");
      out.write("}\n");
      out.write("#id td{\n");
      out.write("\tpadding: 3px 0px 3px 0px;\n");
      out.write("}\n");
      out.write("#header{\n");
      out.write("\tbackground-color: gray;\n");
      out.write("\tcolor: white;\n");
      out.write("}\n");
      out.write("#one{\n");
      out.write("\tbackground-color: #FAFAFA;\n");
      out.write("}\n");
      out.write("#two{\n");
      out.write("\tbackground-color: #D8D8D8;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<table style=\"width: 100%;height: auto;border: 10px;cursor: pointer;\">\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td style=\"width: 97%;\"><img alt=\"All Reports\" src=\"images/Background/report.png\" onclick=\"window.location.assign('Reports.jsp');\" style=\"float:right;\"></td>\n");
      out.write("\t\t\t<td><img alt=\"Home\" src=\"images/Background/House-icon.png\" onclick=\"window.location.assign('HomeForm.jsp');\" style=\"float:right;\"></td>\n");
      out.write("\t\t\t<td ><img alt=\"Save To Excel\" src=\"images/Background/Excel-icon (2).png\"  id=\"saveToExcel\" style=\"float:right;\"/></td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr></tr>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("<form name=\"myform\" method=\"post\">\n");
	
	report.ManageReports mo;
	mo = new report.ManageReports("jdbc/re");
	
	String order_dt="",del_datetiem="",pageType="",order_type="";
	//order_dt=request.getParameter("order_dt");
	String payment_type="";
	payment_type=request.getParameter("payment_type");	
	pageType=request.getParameter("pageType");
	order_type=request.getParameter("order_type");
	
	mo.listDeliveryDailyReportAllDetailsNew(payment_type,order_type);
	
	String criteria="ALL";
	String orderNo="";
	String custCode="";
	String custName="";
	String buildingNo="";
	String block="";
	String wing="";
	String building="";
	String area="";
	String orderDate="";
	String lastModifiedDate="";
	String totalItems="";
	String totalValueMrp="";
	float totalValuePrice=0.0f;
	String discountAmt="";
	String advanceAmt="";
	float balanceAmt=0.0f;
	float changeAmt=0.0f;
	float paidAmt=0.0f;
	float expectedAmt=0.0f;
	String deliveryStaffName="";
	String statusCode="";
    float delchgs=0.0f;
    String payment="";
    double adamt=0.0f;  
    float diffamt=0.0f;  
    float grand_total_value=0.0f;
    double grand_total_adamt=0.0f;
    float grand_total_del=0.0f;
    float grand_total_bal=0.0f;
	float grand_total_change=0.0f;	
	float grand_total_exp=0.0f;	
	float grand_total_paid=0.0f;	
	float grand_total_diff=0.0f;
	
	DecimalFormat df = new DecimalFormat("###,###.0");	

      out.write('\n');
      out.write('\n');
     
	if(!order_type.equals("ALL")){

      out.write("\n");
      out.write("\t\t<br><center><b> Difference Report</center> \n");

	   }else{

      out.write("\n");
      out.write("\t\t<br><center><b> All Order Details</center> \n");

		}

      out.write("\n");
      out.write("\t\t<br>\t&nbsp\t Type &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp:  ");
      out.print(pageType);
      out.write("\n");
      out.write("\t\t<br>\t&nbsp\t Criteria&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp:  ");
      out.print(criteria);
      out.write("\n");
      out.write("      \n");
      out.write("\t\t<input type=\"hidden\" name=\"order_dt\" value=\"\">\n");
      out.write("\t\t<input type=\"hidden\" name=\"orderNo\" value=\"\">\n");
      out.write("\t<div id=\"reportDiffAll\" style=\"display: none;\">\n");
      out.write("\t");

		int i=0;
		int cnt=0;
		ArrayList<SalesOutputBean> lisOutputBeans = new ArrayList();
		
      	while(mo.rs.next()) {
	      	i++;
      		orderNo = mo.rs.getString("order_num");
      		custCode = mo.rs.getString("custcode");
      		custName = mo.rs.getString("custname");
      		buildingNo = mo.rs.getString("building_no");
      		block = mo.rs.getString("block");
      		wing = mo.rs.getString("wing");
      		building = mo.rs.getString("building");
      		area = mo.rs.getString("area");
      		orderDate = mo.rs.getString("order_date");
      		lastModifiedDate = mo.rs.getString("lastmodifieddate");
      		totalItems = mo.rs.getString("total_items");
      		totalValueMrp = mo.rs.getString("total_value_mrp");
      		totalValuePrice = mo.rs.getFloat("total_value");
      		discountAmt = mo.rs.getString("discount_amt");
      		advanceAmt = mo.rs.getString("advance_amt");
      		balanceAmt = mo.rs.getFloat("balance_amt");
      		changeAmt = mo.rs.getFloat("change_amt");
      		paidAmt = mo.rs.getFloat("paid_amt");
      		expectedAmt = mo.rs.getFloat("expected_amt");
      		deliveryStaffName = mo.rs.getString("dstaff_name");
      		statusCode = mo.rs.getString("status_code");
      		delchgs = mo.rs.getFloat("delv_charges");
      		payment = mo.rs.getString("payment_type_desc");
      		
      			grand_total_value = totalValuePrice + grand_total_value;
      			grand_total_del= delchgs + grand_total_del;
      			grand_total_bal= balanceAmt +grand_total_bal;      			
      			grand_total_change= changeAmt  +grand_total_change;      			
	    		grand_total_paid=paidAmt+grand_total_paid;	    		
	    		grand_total_exp = expectedAmt + grand_total_exp;
	 
	    		SalesOutputBean outputBean = new SalesOutputBean();
	      		outputBean.setOrderNo("<a title=\""+mo.rs.getString(12)+","+mo.rs.getString(13)+","+mo.rs.getString(14)+","+mo.rs.getString(15)+","+mo.rs.getString(8)+"\""+
							"href=\"Javascript:passVar('"+orderNo+"');\">"+orderNo+"</a>");
	      		outputBean.setOrderNo1(orderNo);
	      		outputBean.setCustomerCode(custCode);
	      		outputBean.setCustName(custName);
	      		outputBean.setBuildingNo(buildingNo);
	      		outputBean.setBlock(block);
	      		outputBean.setWing(wing);
	      		outputBean.setBuilding(building);
	      		outputBean.setArea("<span align=\"center\" title=\""+mo.rs.getString(12)+","+mo.rs.getString(13)+","+mo.rs.getString(14)+","+mo.rs.getString(15)+","+mo.rs.getString(8)+"\">"+ area+"</span>");
	      		outputBean.setArea1(area);
	      		outputBean.setOrder_date(order_dt);
	      		outputBean.setLastModifiedDate(lastModifiedDate);
	      		outputBean.setTotalItems(totalItems);
	      		outputBean.setTotalValueMrp(totalValueMrp);
	      		outputBean.setTotalValuePrice((totalValuePrice+"").trim());
	      		outputBean.setDiscountAmt(discountAmt);
	      		if(advanceAmt != null && discountAmt != null){
					adamt = Double.parseDouble(advanceAmt) - Double.parseDouble(discountAmt);
					grand_total_adamt= adamt + grand_total_adamt;	
			    }
	      		outputBean.setAdvanceAmt((adamt+"").trim());
	      		
	      		outputBean.setBalanceAmt((balanceAmt+"").trim());
	      		outputBean.setChangeAmt((changeAmt+"").trim());
	      		outputBean.setPaidAmt((paidAmt+"").trim());
	      		outputBean.setExpectedAmount((expectedAmt+"").trim());
	      		outputBean.setDeliveryStaffName(deliveryStaffName);
	      		outputBean.setStatus(statusCode);
	      		outputBean.setDelchgs((delchgs+"").trim());
	      		outputBean.setPayment(payment);
	      		
	      		diffamt = expectedAmt;// - paidAmt;
				grand_total_diff = diffamt + grand_total_diff;
				outputBean.setDiffamt((diffamt+"").trim());
				lisOutputBeans.add(outputBean);
	    		
		cnt++;
		
      	}
      	mo.closeAll();
      	
      	
      	JsonOutputBean jsonOutputBean = new JsonOutputBean();
      	jsonOutputBean.setOutputData(lisOutputBeans);
      	

 	 	System.out.println(new Gson().toJson(jsonOutputBean));
 	 	out.println(new Gson().toJson(jsonOutputBean));

      out.write("\n");
      out.write("</div>\n");
      out.write("<div id=\"reportDiffAllGrid\"></div>\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("a:link {color: blue}\n");
      out.write("a:hover {background: blue;color: white}\n");
      out.write("a:active {background: blue;color: white}\n");
      out.write("</style>\n");
      out.write("\t  \n");
      out.write("<!-- <div id=\"div4\" style=\"VISIBILITY:visible\"><table><tr><td><a href=\"Javascript:Pass();\">Save to excel</a></td></tr></table></div> -->\n");
      out.write("<script>\n");
      out.write("function passVar(code){\n");
      out.write("    \tdocument.myform.orderNo.value=code;\n");
      out.write("\t\tdocument.myform.action=\"print_order.jsp?&backPage=Reports.jsp&buttonFlag=Y\";\n");
      out.write("\t    document.myform.submit();\n");
      out.write("}\n");
      out.write("function Pass(){\n");
      out.write("\t\tdocument.myform.action=\"ReportOrderListWithDate.jsp?Exp=1\";\n");
      out.write("\t    document.myform.submit();\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("$(document).ready(\n");
      out.write("\tfunction(){\n");
      out.write("\t\t\n");
      out.write("\t\tvar gsonObject = jQuery.parseJSON($('#reportDiffAll').html());\n");
      out.write("\t\t\n");
      out.write("\t\t\t var source =\n");
      out.write("            {\n");
      out.write("                localdata: gsonObject.OutputData,\n");
      out.write("                datatype: \"array\"\n");
      out.write("                \n");
      out.write("            };\n");
      out.write("            \n");
      out.write("            \n");
      out.write("         \t$(\"#reportDiffAllGrid\").jqxGrid(\n");
      out.write("            {\t\n");
      out.write("            \ttheme:'darkblue',\n");
      out.write("                height: 400,\n");
      out.write("                source: source,\n");
      out.write("                sortable: true,\n");
      out.write("                filterable: true,\n");
      out.write("                width:'950px',\n");
      out.write("                pageable :true,\n");
      out.write("                groupable: true,\n");
      out.write("                showaggregates: true,\n");
      out.write("                showstatusbar: true,\n");
      out.write("                selectionmode: 'singlecell',\n");
      out.write("               // pagesize: 20,\n");
      out.write("                //columnsresize: true,\n");
      out.write("                //columns:gsonObject.format\n");
      out.write("                columns :\n");
      out.write("                [\n");
      out.write("                \t{\"text\":\"Order No\",\"datafield\":\"orderNo\" ,width:'180px'},\n");
      out.write("                \t{\"text\":\"Order No\",\"datafield\":\"orderNo1\" ,width:'180px',hidden:true},\n");
      out.write("\t                //{\"text\":\"Area\",\"datafield\":\"area\",width:'250px'},{\"text\":\"Area\",\"datafield\":\"area1\",width:'250px',hidden:true},\n");
      out.write("\t                {\"text\":\"Customer Name\",\"datafield\":\"custName\",width:'220px'},\n");
      out.write("\t                //{\"text\":\"Phone\",\"datafield\":\"Phone\",width:'150px'},\n");
      out.write("\t                //{\"text\":\"Order Date\",\"datafield\":\"order_date\",width:'150px'},\n");
      out.write("\t                {\"text\":\"Items\",\"datafield\":\"totalItems\",width:'150px'},\n");
      out.write("\t                //{\"text\":\"Payment\",\"datafield\":\"payment\",width:'150px'},\n");
      out.write("\t                 /*\n");
      out.write("\t                {\"text\":\"Total Amounts \",\"datafield\":\"total_value\",width:'200px',aggregates: [{'Grand Total': function (aggregatedValue, currentValue) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                              if (currentValue) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                                  return aggregatedValue + currentValue;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                              }\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                              return aggregatedValue;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                 }//end of aggreagite sum function\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t   }]\n");
      out.write("\t                },\n");
      out.write("\t                */\n");
      out.write("\t                {\"text\":\"Advance/Discount\",\"datafield\":\"advanceAmt\",width:'200px',aggregates: [{'Grand Total': function (aggregatedValue, currentValue) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                              if (currentValue) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                                  return aggregatedValue + currentValue;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                              }\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                              return aggregatedValue;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                 }//end of aggreagite sum function\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t   }]\n");
      out.write("\t                },/*\n");
      out.write("\t                {\"text\":\"Del Chags\",\"datafield\":\"delchgs\",width:'200px' ,aggregates: [{'Grand Total': function (aggregatedValue, currentValue) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                              if (currentValue) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                                  return aggregatedValue + currentValue;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                              }\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                              return aggregatedValue;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                 }//end of aggreagite sum function\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t   }]\n");
      out.write("\t                },\n");
      out.write("\t               */\n");
      out.write("\t                {\"text\":\"Balance\",\"datafield\":\"balanceAmt\",width:'200px',aggregates: [{'Grand Total': function (aggregatedValue, currentValue) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                              if (currentValue) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                                  return aggregatedValue + currentValue;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                              }\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                              return aggregatedValue;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                 }//end of aggreagite sum function\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t   }]\n");
      out.write("\t                },\n");
      out.write("\t               /*\n");
      out.write("\t               \t {\"text\":\"Change Amount\",\"datafield\":\"changeAmt\",width:'200px',aggregates: [{'Grand Total': function (aggregatedValue, currentValue) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                              if (currentValue) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                                  return aggregatedValue + currentValue;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                              }\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                              return aggregatedValue;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                 }//end of aggreagite sum function\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t   }]\n");
      out.write("\t                },\n");
      out.write("\t                {\"text\":\"Expected\",\"datafield\":\"expectedAmount\",width:'200px',aggregates: [{'Grand Total': function (aggregatedValue, currentValue) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                              if (currentValue) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                                  return aggregatedValue + currentValue;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                              }\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                              return aggregatedValue;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                 }//end of aggreagite sum function\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t   }]\n");
      out.write("\t                \n");
      out.write("\t                },\n");
      out.write("\t                {\"text\":\"Paid\",\"datafield\":\"paidAmt\",width:'200px',aggregates: [{'Grand Total': function (aggregatedValue, currentValue) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                              if (currentValue) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                                  return aggregatedValue + currentValue;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                              }\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                              return aggregatedValue;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                 }//end of aggreagite sum function\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t   }]\n");
      out.write("\t                \n");
      out.write("\t                },\n");
      out.write("\t                {\"text\":\"Difference\",\"datafield\":\"diffamt\",width:'200px',aggregates: [{'Grand Total': function (aggregatedValue, currentValue) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                              if (currentValue) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                                  return aggregatedValue + currentValue;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                              }\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                              return aggregatedValue;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                 }//end of aggreagite sum function\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t   }]\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t               */\n");
      out.write("                ]\n");
      out.write("               \n");
      out.write("               });// closing on JQgrid\n");
      out.write("               \n");
      out.write("               \n");
      out.write("               \n");
      out.write("             \n");
      out.write("             $(\"#saveToExcel\").click(function () {\n");
      out.write("             \n");
      out.write("             \t$('#reportDiffAllGrid').jqxGrid('hidecolumn', 'area');\n");
      out.write("            \t$('#reportDiffAllGrid').jqxGrid('showcolumn', 'area1');\n");
      out.write("            \t\n");
      out.write("            \t$('#reportDiffAllGrid').jqxGrid('hidecolumn', 'orderNo');\n");
      out.write("            \t$('#reportDiffAllGrid').jqxGrid('showcolumn', 'orderNo1');\n");
      out.write("             \t\n");
      out.write("                $(\"#reportDiffAllGrid\").jqxGrid('exportdata', 'xls', 'Diffrence Report');    \n");
      out.write("                \n");
      out.write("                $('#reportDiffAllGrid').jqxGrid('showcolumn', 'area');\n");
      out.write("            \t$('#reportDiffAllGrid').jqxGrid('hidecolumn', 'area1');\n");
      out.write("            \t\n");
      out.write("            \t$('#reportDiffAllGrid').jqxGrid('showcolumn', 'orderNo');\n");
      out.write("            \t$('#reportDiffAllGrid').jqxGrid('hidecolumn', 'orderNo1');\n");
      out.write("                \n");
      out.write("            \t      \n");
      out.write("            });\t//end of excel function  \n");
      out.write("               \n");
      out.write("         }); // end of ready function\n");
      out.write("            \n");
      out.write("            \t\n");
      out.write("\t\t\t\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</form>\n");
      out.write("</body>\n");
      out.write("</html>\t\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
