/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-03-19 05:03:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import inventory.ManageSite;
import java.awt.image.BufferedImage;
import net.sourceforge.barbecue.*;
import javax.imageio.ImageIO;
import java.sql.*;
import javax.naming.*;
import javax.sql.*;
import java.io.*;
import java.awt.*;
import java.util.*;
import java.text.*;
import inventory.ManageInventory;

public final class ReprintTransferInventory_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("div#content\n");
      out.write("{\n");
      out.write("border:2px solid black;\n");
      out.write("border-radius:2em;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");



	String userName = session.getAttribute("UserName").toString();
	
 	Integer siteId = Integer.parseInt(request.getParameter("siteId"));
	Integer desId=Integer.parseInt(request.getParameter("desId"));
	
	String souceName = request.getParameter("sourceName");
	String destName = request.getParameter("destName");
	
	int transfer_id = Integer.parseInt(request.getParameter("ItrnsNumber"));
	String barCode = request.getParameter("Ibarcode"); 
	String[] itemCode = request.getParameterValues("IitemCode");
	String[] itemName = request.getParameterValues("Iitemname");
	String[] itemWeight = request.getParameterValues("Iitemweight"); 
	String [] itemRate = request.getParameterValues("Iitem_rate");
	String itemMrp[] = request.getParameterValues("Iitem_mrp");
	String sourceQty[] = request.getParameterValues("Isource_qty");
	String destQty [] = request.getParameterValues("Ides_qty"); 
	String[] transferQty = request.getParameterValues("Itransfer_qty");
	String [] acceptQty = request.getParameterValues("Iaccept_qty");
	String[] priceVersion = request.getParameterValues("priceversion");
	String [] Status = request.getParameterValues("Istatus"); 
	//String[] box_qty = request.getParameterValues("box_qty_save");
	//String [] status = request.getParameterValues("IStatus");
	String IdestQty11[] = request.getParameterValues("Ides_qty");
	
	
	Integer totalItems =Integer.parseInt(request.getParameter("grandTotalItems"));
	//Integer totalQty = Integer.parseInt(request.getParameter("grandTotalQty"));
	int totalQty = 0;
	System.out.println("======\n\\n item code "+itemCode.length+"\n item name length "+IdestQty11.length);
	
	for(String transfer :acceptQty){
		System.out.println("== transfer "+transfer);
		totalQty = totalQty + Integer.parseInt(transfer);
		
		
	}
	
	Context initContext = new InitialContext();
	Context envContext  = (Context)initContext.lookup("java:/comp/env");
	ManageInventory  objMI = new ManageInventory("jdbc/js");
	Barcode objBarcode = BarcodeFactory.createCode128C(transfer_id+"");
	String ImagePath = (String) envContext.lookup("imagesfile");
	ImagePath = config.getServletContext().getRealPath(ImagePath)+"/"+transfer_id+".PNG";
	objBarcode.setDrawingText(true);
	File f = new File(ImagePath);            	
    BarcodeImageHandler.savePNG(objBarcode, f);
   

      out.write("\n");
      out.write("\t<center><h1>Received Inventory Successfully</h3>\n");
      out.write("\t<div id=\"content\" align=\"center\">\n");
      out.write("\t<br/>\n");
      out.write("\t<img src=\"images/barcodeImages/");
      out.print(transfer_id);
      out.write(".PNG\" width=\"120px;\"/><h3>Received Inventory</h3>\n");
      out.write("\t<b><table style=\"border-collapse: collapse;\">\n");
      out.write("\t\t<tr><td>Bill no </td><td>: </td><td> ");
      out.print( transfer_id );
      out.write(" </td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>From </td><td>: </td><td>");
      out.print( souceName);
      out.write("</td></tr>\n");
      out.write("\t\t<tr><td>User </td><td>: </td><td> ");
      out.print( userName );
      out.write(" </td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>To </td><td>: </td><td>");
      out.print( destName);
      out.write("</td></tr>\n");
      out.write("\t</table></b>\n");
      out.write("\t<table border=\"1\" style=\"border-collapse: collapse;border-left:1px;border-top:1px; \">\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<th style=\"width:40\">No.</th>\n");
      out.write("\t\t\t<th style=\"width:280\"> Item Name </th>\n");
      out.write("\t\t\t<th style=\"width:80\"> Weight </th>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t<th style=\"width:70\"> MRP </th>\n");
      out.write("\t\t\t<th style=\"width:80\"> JS price </th>\n");
      out.write("\t\t\t<th style=\"width:80\"> Source Qty </th>\n");
      out.write("\t\t\t<th style=\"width:80\"> Dest.Qty </th>\n");
      out.write("\t\t\t<th style=\"width:80\"> Acc.Qty </th>\n");
      out.write("\t\t\t<!-- <th style=\"width:80\"> Remain Qty </th>\n");
      out.write("\t\t\t<th style=\"width:80\"> After Trans. Qty </th> -->\n");
      out.write("\t\t\t<th style=\"width:80\"> Status </th>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t");
 
			String inventoryStatus =null;
			for(int i=0;i<itemCode.length;i++){
				if(Status[i].equals("CHNGQTY-RCVD LESS"))
					inventoryStatus="Receive Less";
				else if(Status[i].equals("CHNGQTY-RCVD MORE"))
					inventoryStatus= "Receive More";
				else if(Status[i].equals("NOT TRANSFER"))
					inventoryStatus= "Not Receive ";
				else if(Status[i].equals("TRANSFER"))
					inventoryStatus= "Receive ";
				
				System.out.println("item code "+itemCode[i]+"\n objMI.getItemName(itemCode[i]) "+objMI.getItemName(itemCode[i]));
				
				out.print("<tr><td>"+(i+1)+".</td>");
				out.print("<td>"+objMI.getItemName(itemCode[i])+"</td>");
				out.print("<td>"+itemWeight[i]+"</td>");
				out.print("<td>"+itemMrp[i]+"</td>");
				out.print("<td>"+itemRate[i]+"</td>");
				
				/* out.print("<td>"+transferQty[i]+"</td>"); */
				/* out.print("<td>"+(Integer.parseInt(sourceqty[i])-Integer.parseInt(transferqty[i]))+"</td>");
				out.print("<td>"+(Integer.parseInt(sourceQty[i])+Integer.parseInt(acceptQty[i]))+"</td>");
				out.print("<td>"+(Integer.parseInt(IdestQty11[i])-Integer.parseInt(acceptQty[i]))+"</td>");*/
		
				out.print("<td>"+sourceQty[i]+"</td>");
				out.print("<td>"+IdestQty11[i]+"</td>");
				
				out.print("<td>"+acceptQty[i]+"</td>");
				/* out.print("<td>"+sourceQty[i]+"</td>");
				out.print("<td>"+IdestQty11[i]+"</td>"); */
				out.print("<td>"+Status[i]+"</td></tr>");
			}
				
			 
      out.write("\n");
      out.write("\t\t\t </tbody>\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t\t<br/>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<br/>\n");
      out.write("\t\t\t<input type=\"button\" value=\"Print\" style=\"width:100\" onclick=\"printPage('content');\"/>\n");
      out.write("\t\t\t<input type=\"button\" value=\"Back Page\" style=\"width:100\" onclick=\"back();\"/>\n");
      out.write("\t\t\t<input type=\"button\" value=\"Home Page\" style=\"width:100\" onclick=\"home();\"/>\n");
      out.write("\t\t\t</center>\n");
      out.write("\t    \t\t\n");

	objMI.closeAll();

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("function printPage(id){\n");
      out.write("\tvar html=\"<html> <style> .hidePrint{display:none;}</style>\";\n");
      out.write("    html+= document.getElementById(id).innerHTML;\n");
      out.write("\n");
      out.write("   var printWin = window.open('','','left=3,top=4,width=700,height=600,toolbar=0,scrollbars=2,status  =0');\n");
      out.write("   printWin.document.write(html);\n");
      out.write("   printWin.document.close();\n");
      out.write("   printWin.focus();\n");
      out.write("   printWin.print();\n");
      out.write("   printWin.close();\n");
      out.write("   window.location=\"EditTransferInventoryForm.jsp\";\n");
      out.write("   }\n");
      out.write("function back(){\n");
      out.write("\twindow.location=\"EditTransferInventoryForm.jsp\";\n");
      out.write("\t}\n");
      out.write("function home(){\n");
      out.write("\twindow.location=\"HomeForm.jsp\";\n");
      out.write("\t}\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
