/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-02-21 05:48:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.naming.*;
import javax.sql.*;
import java.io.*;

public final class saveCheckedOrderData_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	Connection conn = null;
	Statement stmt = null, stat = null, stat1 = null;
	ResultSet rs1 = null;
	String orderNo = request.getParameter("orderNo");
	String bagNo = request.getParameter("bagNo");
	String oldItemValues = request.getParameter("oldItems");
	String newItemsValues = request.getParameter("newItems");
	String userName = session.getAttribute("UserName").toString();
	String objOldItemCode = "";
	String objNewItemCode = "";
	System.out.println("Old : " + oldItemValues);
	System.out.println("New : " + newItemsValues);
	float price = 0.0f, qty = 0.0f, oldPrice = 0.0f;
	boolean ans = false;
	order.ManageOrder mo = new order.ManageOrder("jdbc/js");
	if (!oldItemValues.equals("") && !newItemsValues.equals("")) {
		String[] arrOldItemList;
		String[] arrNewItemList;
		arrOldItemList = oldItemValues.split("##");
		arrNewItemList = newItemsValues.split("##");
		String[] arrOldItem;
		String[] arrNewItem;
		for (int i = 0; i < arrOldItemList.length; i++) {
			//---------get old item code
			arrOldItem = arrOldItemList[i].split("@@");
			objOldItemCode = arrOldItem[0];
			oldPrice = Float.parseFloat(arrOldItem[6]);
			//----------get new item data
			arrNewItem = arrNewItemList[i].split("@@");
			objNewItemCode = arrNewItem[0];
			price = Float.parseFloat(arrNewItem[5]);
			qty = Float.parseFloat(arrNewItem[4]);
			ans = mo.saveCheckedOrderItems(orderNo, objOldItemCode,
					oldPrice, objNewItemCode, price, qty);

		}
		if (ans) {
			ans = false;
			ans = mo.saveCheckedOrder(orderNo, userName, bagNo);
			if (ans) {
				try {
					Context initContext = new InitialContext();
					Context envContext = (Context) initContext
							.lookup("java:/comp/env");
					DataSource ds = (DataSource) envContext
							.lookup("jdbc/js");
					conn = ds.getConnection();
					stmt = conn.createStatement();
					stat = conn.createStatement();
					String query = "select od.item_code, od.qty, od.price_version, o.site_id from order_detail od, orders o "
							+ "where o.order_num = od.order_num and od.order_num = '"
							+ orderNo + "'";
					ResultSet rs = stmt.executeQuery(query);
					int count = 0;
					while (rs.next()) {
						String query1 = "update item_master set item_qty = item_qty - "
								+ rs.getInt(2)
								+ " where item_code = '"
								+ rs.getString(1) + "'";
						System.out.println("Master :" + query1);
						stat.executeUpdate(query1);
						query1 = "update item_price set item_pv_qty = item_pv_qty - "
								+ rs.getInt(2)
								+ " where item_code = '"
								+ rs.getString(1)
								+ "' "
								+ " and price_version  = " + rs.getInt(3);
						System.out.println("Price :" + query1);
						stat.executeUpdate(query1);
						query1 = "update item_site_inventory set item_site_qty = item_site_qty - "
								+ rs.getInt(2)
								+ " where item_code = '"
								+ rs.getString(1)
								+ "' "
								+ "and price_version  = "
								+ rs.getInt(3)
								+ " and site_id = " + rs.getInt(4);
						System.out.println("Site :" + query1);
						stat.executeUpdate(query1);
					}
				} catch (Exception e) {
					e.printStackTrace();
				}
				out.println("Swap");
			} else {
				out.println("ERROR");
			}
		}
		conn.close();
		
	} else {
		ans = mo.saveCheckedOrder(orderNo, userName, bagNo);
		if (ans) {
			try {
				Context initContext = new InitialContext();
				Context envContext = (Context) initContext
						.lookup("java:/comp/env");
				DataSource ds = (DataSource) envContext
						.lookup("jdbc/js");
				conn = ds.getConnection();
				stmt = conn.createStatement();
				stat = conn.createStatement();
				stat1 = conn.createStatement();
				String query = "select od.item_code, od.qty, od.price_version, o.site_id from order_detail od, orders o "
						+ "where o.order_num = od.order_num and od.order_num = '"
						+ orderNo + "'";
				ResultSet rs = stmt.executeQuery(query);
				int count = 0;
				while (rs.next()) {
					Statement st = conn.createStatement();
					String query1 = "update item_master set item_qty = item_qty - "
							+ rs.getInt(2)
							+ " where item_code = '"
							+ rs.getString(1) + "'";
					System.out.println("Master :" + query1);
					st.executeUpdate(query1);
					query1 = "update item_price set item_pv_qty = item_pv_qty - "
							+ rs.getInt(2)
							+ " where item_code = '"
							+ rs.getString(1)
							+ "' "
							+ " and price_version  = " + rs.getInt(3);
					System.out.println("Price :" + query1);
					st.executeUpdate(query1);
					query1 = "update item_site_inventory set item_site_qty = item_site_qty - "
							+ rs.getInt(2)
							+ " where item_code = '"
							+ rs.getString(1)
							+ "' "
							+ "and price_version  = "
							+ rs.getInt(3)
							+ " and site_id = " + rs.getInt(4);
					System.out.println("Site :" + query1);
					st.executeUpdate(query1);
				}
			} catch (Exception e) {
				e.printStackTrace();
				
			}
			out.println("Success");
		} else {
			out.println("ERROR");
		}
		conn.close();
	}
	mo.closeAll();

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
