/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-02-12 05:45:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.*;
import payment.*;
import java.sql.*;
import javax.naming.*;
import javax.sql.*;

public final class SingelItemStack_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"ReportErrorPage.jsp?page=SingleItemStack.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "leftsidemenu.jsp", out, false);
      out.write("\r\n");
      out.write("<script src=\"js/jquery-1.2.6.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"js/singleItemStock.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/singleItemStock.css\" />\r\n");
      out.write(" <link href=\"css/StockMovementReportForm.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\r\n");
      out.write("<!-- files for JqxWidget grid  -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"js/jqwidgets/styles/jqx.base.css\" type=\"text/css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"js/jqwidgets/styles/jqx.darkblue.css\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery-1.10.2.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxcore.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxdata.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxbuttons.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxscrollbar.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxlistbox.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxcalendar.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxdatetimeinput.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.filter.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.selection.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.sort.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.pager.js\"></script>\r\n");
      out.write("     <script type=\"text/javascript\" src=\"js/jqwidgets/jqxmenu.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxlistbox.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxdropdownlist.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxdata.export.js\"></script> \r\n");
      out.write("     <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.export.js\"></script> \r\n");
      out.write("      <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.columnsresize.js\"></script> \r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.grouping.js\"></script>      \r\n");
      out.write("   <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.columnsresize.js\"></script> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<td width=\"50%\" valign=\"top\" style=\"font-family: arial;\">\r\n");
      out.write("\t<h2 style=\"float: left;\">Item wise Stock Report</h2>\r\n");
      out.write("\t<table style=\"width: 100%;\">\r\n");
      out.write("\t<tr style=\"display: none;cursor: pointer;\" id=\"excelRow\"><td colspan=\"2\"><img alt=\"Save To Excel\" src=\"images/Background/Excel-icon (2).png\"  id=\"saveToExcel\" style=\"float:right;\"/></td></tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td style=\"width: 25%; border: 1px solid black;\" valign=\"top\" align=\"center\">\r\n");
      out.write("\t\t\t\t<h4>Search Item</h4>\r\n");
      out.write("\t\t\t\t<table style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"left\" style=\"width: 37%;\">\r\n");
      out.write("\t\t\t\t\t\t\tItem <font color=\"blue\"><u>N</u></font>ame\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 1%;\">\r\n");
      out.write("\t\t\t\t\t\t\t:\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"left\" style=\"width: 55%;\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"item_name\" id=\"item_name_id\" style=\"width: 95%;\" accesskey=\"n\"/>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\tItem <font color=\"blue\"><u>C</u></font>ode\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t:\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"item_code\" id=\"item_code_id\" style=\"width: 95%;\" accesskey=\"c\"/>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"left\" valign=\"top\">\r\n");
      out.write("\t\t\t\t\t\t\tItem <font color=\"blue\"><u>G</u></font>roup\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td valign=\"top\">\r\n");
      out.write("\t\t\t\t\t\t\t:\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								Connection conn = null;
								Statement stmt = null, stat = null;
								ResultSet rs = null, rs2 = null;
								try {
									String name, desc;
									int rowcount;
									Context initContext = new InitialContext();
									Context envContext = (Context) initContext.lookup("java:/comp/env");
									//DataSource ds = (DataSource) envContext.lookup("jdbc/js");
									DataSource ds = (DataSource) envContext.lookup("jdbc/re");
									conn = ds.getConnection();
									stmt = conn.createStatement();
									rs = stmt.executeQuery("select item_group_code, item_group_desc from item_group");
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<SELECT name=\"item_group\" id = \"item_group_id\" size=\"6\" accesskey=\"g\" style=\"width: 99%;\">\r\n");
      out.write("\t\t\t\t\t\t\t<OPTION VALUE=\"\"> Select Group</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t");

								rowcount = 0;
								while (rs.next()) {
									name = rs.getString(1);
									desc = rs.getString(2);
									if (rowcount == 0) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<OPTION VALUE=\"");
      out.print(name);
      out.write('"');
      out.write('>');
      out.print(desc);
      out.write("</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t");

									} else {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<OPTION VALUE=\"");
      out.print(name);
      out.write('"');
      out.write('>');
      out.print(desc);
      out.write("</OPTION>\r\n");
      out.write("\t\t\t\t\t\t\t");

									}
								rowcount++;
								}
								rowcount = 0;
								rs.close();
								stmt.close();
								conn.close();
							} catch (Exception e){}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</SELECT>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\tItem <font color=\"blue\"><u>B</u></font>arcode\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t:\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"item_barcode\" id=\"item_barcode_id\" style=\"width: 98%;\" accesskey=\"b\"/>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"3\" style=\"padding-top: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" accesskey=\"r\" onclick=\"window.location.reload();\" value=\"Refresh<Alt+r>\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" accesskey=\"s\" onclick=\"getItemList();\" value=\"Search<Alt+s>\"/>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td id = \"item_list_td\" valign=\"top\" style=\" width: 70%;\" align=\"center\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\t\t\r\n");
      out.write("<div id=\"popupContact\">\r\n");
      out.write(" \t<h3>Current Stock Information</h3> <a id=\"popupContactClose\">x</a>\r\n");
      out.write("\t<ul style=\"width: 100%;\">\r\n");
      out.write("\t<li class=\"list\" id='list1'><b>Item Name :&nbsp;</b>null</li>\r\n");
      out.write("\t<li class=\"list\" id='list2'><b>Item Weight :&nbsp;</b>null</li>\r\n");
      out.write("\t<li class=\"list\" id='list3'><b>Total Quantity :&nbsp;</b>null</li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<div id = \"stack_info\">\r\n");
      out.write("\t</div>\t\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"backgroundPopup\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
