/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-02-12 05:47:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class StockMovementReportForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write(" <title>Retail Management-Janta Stores</title>\n");
      out.write(" <!-- files for JqxWidget grid  -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"js/jqwidgets/styles/jqx.base.css\" type=\"text/css\" />\n");
      out.write("    <link rel=\"stylesheet\" href=\"js/jqwidgets/styles/jqx.darkblue.css\" type=\"text/css\" />\n");
      out.write("\t<link rel=\"stylesheet\" href=\"js/jqwidgets/styles/jqx.ui-redmond.css\" type=\"text/css\" />\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/gettheme.js\"></script>\n");
      out.write("    \n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery-1.10.2.min.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxcore.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxdata.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxbuttons.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxscrollbar.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxlistbox.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxcalendar.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxdatetimeinput.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.filter.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.selection.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.sort.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.pager.js\"></script>\n");
      out.write("     <script type=\"text/javascript\" src=\"js/jqwidgets/jqxmenu.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxlistbox.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxdropdownlist.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.columnsresize.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.grouping.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxdata.export.js\"></script> \n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.export.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqwidgets/jqxgrid.aggregates.js\"></script>\n");
      out.write("     \n");
      out.write(" <script type=\"text/javascript\" src=\"js/StockMovementReportForm.js\"></script>\n");
      out.write(" <link href=\"css/StockMovementReportForm.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<table style=\"width: 100%;height: auto;border: 10px;\">\n");
      out.write("\t\t<tr style=\"cursor: pointer;\">\n");
      out.write("\t\t\t<td style=\"width: 97%;\"><img alt=\"All Reports\" src=\"images/Background/report.png\" onclick=\"window.location.assign('Reports.jsp');\" style=\"float:right;\"></td>\n");
      out.write("\t\t\t<td><img alt=\"Home\" src=\"images/Background/House-icon.png\" onclick=\"window.location.assign('HomeForm.jsp');\" style=\"float:right;\"></td>\n");
      out.write("\t\t\t<td></td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr></tr>\n");
      out.write("\t</table>\n");
      out.write("<center><h3>Stock Movement Report</h3></center>\n");
      out.write("<table>\n");
      out.write("\t<tr style=\"font-weight: bold;\">\n");
      out.write("\t\t<td>Item Name&nbsp;:&nbsp;<input type=\"text\" size=\"50\" id='searchItemName'></td>\n");
      out.write("\t\t<td><font style=\"color: blue;\">F</font>rom Date</td>\n");
      out.write("\t\t<td><div id=\"range1\"></div></td>\n");
      out.write("\t\t<td><font style=\"color: blue;\">T</font>o Date</td>\n");
      out.write("\t\t<td><div id=\"range2\"></div></td>\n");
      out.write("\t\t<td><button onclick=\"getSuggestedItem();\" >Search Item</button></td>\n");
      out.write("\t\t\n");
      out.write("\t</tr>\n");
      out.write("</table><br/>\n");
      out.write("<ul style=\"width: 100%;\">\n");
      out.write("\t<li class=\"list\" id='list1'><b>Item Name :&nbsp;</b>null</li>\n");
      out.write("\t<li class=\"list\" id='list2'><b>Item Weight :&nbsp;</b>null</li>\n");
      out.write("\t<li class=\"list\" id='list3'><b>Total Quantity :&nbsp;</b>null</li>\n");
      out.write("</ul>\n");
      out.write("<div class=\"outer\"><center><b>Purchase</b><img alt=\"Save To Excel\" class=\"excel\" src=\"images/Background/Excel-icon (2).png\" id=\"purchaseToExcel\"/></center>\n");
      out.write("<div class=\"result\" id=\"purchase\"></div></div>\n");
      out.write("<div class=\"outer\"><center><b>Transfer</b><img alt=\"Save To Excel\" class=\"excel\" src=\"images/Background/Excel-icon (2).png\"  id=\"transferToExcel\" /></center>\n");
      out.write("<div class=\"result\" id='transfer'></div></div>\n");
      out.write("<div class=\"outer\"><center><b>Sales</b><img alt=\"Save To Excel\" class=\"excel\" src=\"images/Background/Excel-icon (2).png\"  id=\"salesToExcel\" /></center>\n");
      out.write("<div class=\"result\" id='sales'></div></div>\n");
      out.write("<div class=\"outer\"><center><b>Current Stock</b><img alt=\"Save To Excel\" class=\"excel\" src=\"images/Background/Excel-icon (2).png\"  id=\"stockToExcel\" /></center><div class=\"result\" id='stock'></div></div>\n");
      out.write("\n");
      out.write("<div id =\"sales_info\" style=\"width: 100%;height: 100%;\"></div>\n");
      out.write("\n");
      out.write("<div id=\"popupContact\" style=\"height: auto;width: 730px;\" >\n");
      out.write("\t<a id=\"popupContactClose\"><img src=\"images/Background/Button-Close-icon.png\"></a>\n");
      out.write("\t<div id = \"stack_info\">\n");
      out.write("\t</div>\t\n");
      out.write("</div>\n");
      out.write("<div id=\"backgroundPopup\" style=\"background-color: transparent;\"></div>\t\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
