/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-02-25 05:19:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.naming.*;
import javax.sql.*;
import java.text.*;

public final class TrackingForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"ErrorPage.jsp?page=TrackingForm.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write(" \n");
      out.write("\n");
      out.write("\t\n");
      out.write("\t");

	session.getAttribute("UserName").toString();
	//System.out.println("session bachka maapping : "+session +" \n user "+session.getAttribute("UserName").toString());
	
      out.write('\n');
      out.write(' ');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\t\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.10.2.min.js\"></script>\n");
      out.write("<script src=\"js/TrackingForm.js\"></script>\n");
      out.write("<script src=\"js/ua.js\"></script>\n");
      out.write("<script src=\"js/ftiens4.js\"></script>\n");
      out.write("<script src=\"js/demoOrderFramelessNode.js\"></script>\n");
      out.write("\n");
      out.write("<form name=\"myform\" method=\"post\" >\n");
      out.write("\t<table width=100%>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<TD style='background: #CCCCFF' width=\"16%\" valign=\"top\" align=\"left\">\n");
      out.write("\t\t\t\t");
	
	String code="";
	String desc="";
	order.ManageOrder mo;
	mo = new order.ManageOrder("jdbc/js");  
	mo.getDeliveryStaffList();
	try {
	 	
	 	while (mo.rs1.next()) {
		 	code = mo.rs1.getString(1);
		 	desc = mo.rs1.getString(2);
			
      out.write(" <script>\n");
      out.write("\t\t\t    auxDP = insFld(aux24, gFld('");
      out.print(desc);
      out.write("', 'javascript:showHint(\"OrderProcessingTransitForm.jsp?subValue=Transit3&code=");
      out.print(code);
      out.write("&desc=");
      out.print(desc);
      out.write("\")'))\t\t    \n");
      out.write("\t\t\t    \n");
      out.write("    \t\t</script> ");

		}
		mo.closeAll();
	}catch (Exception e) {
		e.getMessage();
		e.printStackTrace();
	}

      out.write(" <script>initializeDocument()</script></td>\n");
      out.write("\n");
      out.write("\t\t\t<td>\n");
      out.write("\t\t\t\t<div id=\"displayDiv\"></div>\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"backPage\" value=\"TrackingForm.jsp\">\n");
      out.write("\t\t</tr>\n");
      out.write("\t</table>\n");
      out.write("</form>\t\n");
      out.write("\n");

		String temp=request.getParameter("subValue"); 
		String orderNum=request.getParameter("ordernum");
		String printdeliver=request.getParameter("printdeliver");
		
		if(printdeliver!=null){
			if(printdeliver.equals("1")){		

      out.write("\n");
      out.write("\t\t\t\t<script>func(");
      out.print(orderNum);
      out.write(")</script>\n");

		}
	}

      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
